language: python
python:
  - "3.6"
install:
  - pip install mysql-connector
script: 
  - git branch
  - ls
  - python unit_test.py
  # - cd ./Logfile
  - git config --global user.name "Debug1995"
  - git config --global user.email "199511zc@gmail.com"
  - git pull
  - git add unittest_log.txt
  - git commit -m "unittest log"
  - git push --force "https://${GH_token}@${GH_ref}" master:master
# after_success:
#   - cd ./Logfile
#   - git config --global user.name "Debug1995"
#   - git config --global user.email "199511zc@gmail.com"
#   - git add .
#   - git commit -m 'unittest log'
#   - git push --force "https://${GH_token}@${GH_ref}" master:master
env:
  global:
    - GH_ref: github.com/Debug1995/JoinMe.git