language: python
python:
  - "3.6"
install:
  - pip install mysql-connector
script: 
  # - ls
  # - ls -l unittest_log.txt
  - python unit_test.py
  - git branch
  - ls
  # - git init
  # - ls -l unittest_log.txt
  # # - cd ./Logfile
  # - git config --global user.name "Debug1995"
  # - git config --global user.email "199511zc@gmail.com"
  # - git pull
  # - git add .
  # - git commit -m "unittest log"
  # - git push --force "https://${GH_token}@$github.com/Debug1995/JoinMe.git" master:master
after_success:
  - git config --global user.name "Debug1995"
  - git config --global user.email "199511zc@gmail.com"
  # - git checkout master
  # - git pull
  - git add unittest_log.txt
  - git commit -m 'unittest_log'
  - git push "https://${GH_token}@${GH_ref}" travis_ci:master
branches:
  only:
    - travis_ci
env:
  global:
    - GH_ref: github.com/Debug1995/JoinMe.git