language: python
python:
  - "3.6"
branches:
  only:
    - cz2465
install:
  - pip install mysql-connector
script: 
  - python unit_test.py
after_success:
  - cd ./Logfile
  - git init
  - git config --global user.name "Debug1995"
  - git config --global user.email "199511zc@gmail.com"
  - git add .
  - git commit -m 'unittest log'
  - git push --force "https://Debug1995:${GH_token}@${GH_ref}" master:master
env:
  global:
    - GH_ref: https://github.com/Debug1995/JoinMe.git