language: python
python:
  - "3.6"
install:
  - pip install mysql-connector
script: 
  - ls -l unittest_log.txt
  - python unit_test.py test
  - ls -l unittest_log.txt
  - python unit_test.py test
  - ls -l unittest_log.txt
  - git config --global user.name "Debug1995"
  - git config --global user.email "199511zc@gmail.com"
  - git add unittest_log.txt
  - git commit -m "unittest log"
  # - git remote add
  - git push --force --quiet "https://${GH_token}@${GH_ref}" travis_ci:travis_ci
#   - git config --global user.name "Debug1995"
#   - git config --global user.email "199511zc@gmail.com"
#   # - git checkout master
#   # - git pull
#   # - git add .
#   # - git commit -m 'unittest_log'
#   - git push "https://${GH_token}@${GH_ref}" travis_ci:travis_ci
branches:
  only:
    - travis_ci
env:
  global:
    - GH_ref: github.com/Debug1995/JoinMe.git