#!/usr/local/bin/python
import os
import re
import sys

import subprocess

PYLINT_PASS_THRESHOLD = 2


def main():
    sub = subprocess.check_output("git diff --staged --name-only HEAD".split())
    sub = sub.decode("utf-8")
    py_files_changed = []
    for file in str(sub).split('\n'):
        if file[-3:] == ".py":
   		    py_files_changed.append(file)

    results = {}
    for file in py_files_changed:
        r = os.popen("pylint -f text %s" % file)
        text = r.read()
        ans1 = text.strip().split()[-2]
        ans2 = text.strip().split()[-1]
        score1 = ans1[0: 4]
        score2 = ans2[0: 4]
        try:
        	score = float(score1)
        except:
        	score = float(score2)
        results[file] = score

    if len(results.values()) > 0:
        print("===============================================")
        print("Final Results:")
        for file in results:
            result = results[file]
            grade = "FAIL" if result < PYLINT_PASS_THRESHOLD else "pass"
            print(grade, file, result)

    if any([(result < PYLINT_PASS_THRESHOLD)
            for result in results.values()]):
        print("git: fatal: commit failed, Pylint tests failing.")
        sys.exit(1)
    else:
        sys.exit(0)


if __name__ == "__main__":
    main()