# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hosteventdisplaydialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HostEventDisplayDialog(object):
    def setupUi(self, HostEventDisplayDialog):
        HostEventDisplayDialog.setObjectName("HostEventDisplayDialog")
        HostEventDisplayDialog.resize(745, 453)
        HostEventDisplayDialog.setStyleSheet("")
        self.UserName_13 = QtWidgets.QLabel(HostEventDisplayDialog)
        self.UserName_13.setGeometry(QtCore.QRect(630, 380, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.UserName_13.setFont(font)
        self.UserName_13.setStyleSheet("border-image: \\*url();")
        self.UserName_13.setObjectName("UserName_13")
        self.UserName_8 = QtWidgets.QLabel(HostEventDisplayDialog)
        self.UserName_8.setGeometry(QtCore.QRect(10, 220, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.UserName_8.setFont(font)
        self.UserName_8.setStyleSheet("border-image: \\*url();")
        self.UserName_8.setObjectName("UserName_8")
        self.HostIDOutput = QtWidgets.QLabel(HostEventDisplayDialog)
        self.HostIDOutput.setGeometry(QtCore.QRect(60, 220, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.HostIDOutput.setFont(font)
        self.HostIDOutput.setStyleSheet("border-image: \\*url();")
        self.HostIDOutput.setObjectName("HostIDOutput")
        self.line_2 = QtWidgets.QFrame(HostEventDisplayDialog)
        self.line_2.setGeometry(QtCore.QRect(0, 50, 600, 2))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line_2.setFont(font)
        self.line_2.setStyleSheet("border-image: \\*url();\n"
"background-color: rgb(19, 35, 255);\n"
"")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.DescriptionOutput = QtWidgets.QLabel(HostEventDisplayDialog)
        self.DescriptionOutput.setGeometry(QtCore.QRect(10, 120, 551, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.DescriptionOutput.setFont(font)
        self.DescriptionOutput.setStyleSheet("border-image: \\*url();")
        self.DescriptionOutput.setObjectName("DescriptionOutput")
        self.graphicsView_14 = QtWidgets.QGraphicsView(HostEventDisplayDialog)
        self.graphicsView_14.setGeometry(QtCore.QRect(630, 402, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.graphicsView_14.setFont(font)
        self.graphicsView_14.setStyleSheet("border-image: url(./pin-2.png)")
        self.graphicsView_14.setObjectName("graphicsView_14")
        self.UserName_5 = QtWidgets.QLabel(HostEventDisplayDialog)
        self.UserName_5.setGeometry(QtCore.QRect(300, 180, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.UserName_5.setFont(font)
        self.UserName_5.setStyleSheet("border-image: \\*url();")
        self.UserName_5.setObjectName("UserName_5")
        self.EventEditButton = QtWidgets.QPushButton(HostEventDisplayDialog)
        self.EventEditButton.setGeometry(QtCore.QRect(606, 60, 81, 34))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EventEditButton.setFont(font)
        self.EventEditButton.setStyleSheet("border-image: \\*url();")
        self.EventEditButton.setObjectName("EventEditButton")
        self.AddressOutput = QtWidgets.QLabel(HostEventDisplayDialog)
        self.AddressOutput.setGeometry(QtCore.QRect(90, 180, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AddressOutput.setFont(font)
        self.AddressOutput.setStyleSheet("border-image: \\*url();")
        self.AddressOutput.setObjectName("AddressOutput")
        self.CityOutput = QtWidgets.QLabel(HostEventDisplayDialog)
        self.CityOutput.setGeometry(QtCore.QRect(340, 180, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.CityOutput.setFont(font)
        self.CityOutput.setStyleSheet("border-image: \\*url();")
        self.CityOutput.setObjectName("CityOutput")
        self.label_2 = QtWidgets.QLabel(HostEventDisplayDialog)
        self.label_2.setGeometry(QtCore.QRect(8, 3, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        font.setPointSize(34)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-image: \\*url();")
        self.label_2.setObjectName("label_2")
        self.UserName = QtWidgets.QLabel(HostEventDisplayDialog)
        self.UserName.setGeometry(QtCore.QRect(8, 55, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.UserName.setFont(font)
        self.UserName.setStyleSheet("border-image: \\*url();")
        self.UserName.setObjectName("UserName")
        self.EventIamge1 = QtWidgets.QGraphicsView(HostEventDisplayDialog)
        self.EventIamge1.setGeometry(QtCore.QRect(580, 112, 131, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EventIamge1.setFont(font)
        self.EventIamge1.setStyleSheet("border-image: url(./DefaultImage.png)")
        self.EventIamge1.setObjectName("EventIamge1")
        self.EventIamge2 = QtWidgets.QGraphicsView(HostEventDisplayDialog)
        self.EventIamge2.setGeometry(QtCore.QRect(580, 200, 131, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EventIamge2.setFont(font)
        self.EventIamge2.setStyleSheet("border-image: url(./DefaultImage.png)")
        self.EventIamge2.setObjectName("EventIamge2")
        self.line_3 = QtWidgets.QFrame(HostEventDisplayDialog)
        self.line_3.setGeometry(QtCore.QRect(0, 80, 600, 2))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line_3.setFont(font)
        self.line_3.setStyleSheet("border-image: \\*url();\n"
"background-color: rgb(19, 35, 255);\n"
"")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.UserName_12 = QtWidgets.QLabel(HostEventDisplayDialog)
        self.UserName_12.setGeometry(QtCore.QRect(620, 90, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.UserName_12.setFont(font)
        self.UserName_12.setStyleSheet("border-image: \\*url();")
        self.UserName_12.setObjectName("UserName_12")
        self.UserName_9 = QtWidgets.QLabel(HostEventDisplayDialog)
        self.UserName_9.setGeometry(QtCore.QRect(300, 220, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.UserName_9.setFont(font)
        self.UserName_9.setStyleSheet("border-image: \\*url();")
        self.UserName_9.setObjectName("UserName_9")
        self.UserName_11 = QtWidgets.QLabel(HostEventDisplayDialog)
        self.UserName_11.setGeometry(QtCore.QRect(10, 340, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.UserName_11.setFont(font)
        self.UserName_11.setStyleSheet("border-image: \\*url();")
        self.UserName_11.setObjectName("UserName_11")
        self.SendEmailButton = QtWidgets.QPushButton(HostEventDisplayDialog)
        self.SendEmailButton.setGeometry(QtCore.QRect(510, 395, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.SendEmailButton.setFont(font)
        self.SendEmailButton.setStyleSheet("border-image: \\*url();")
        self.SendEmailButton.setObjectName("SendEmailButton")
        self.UserName_2 = QtWidgets.QLabel(HostEventDisplayDialog)
        self.UserName_2.setGeometry(QtCore.QRect(9, 90, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.UserName_2.setFont(font)
        self.UserName_2.setStyleSheet("border-image: \\*url();")
        self.UserName_2.setObjectName("UserName_2")
        self.EventIamge3 = QtWidgets.QGraphicsView(HostEventDisplayDialog)
        self.EventIamge3.setGeometry(QtCore.QRect(580, 290, 131, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EventIamge3.setFont(font)
        self.EventIamge3.setStyleSheet("border-image: url(./DefaultImage.png)")
        self.EventIamge3.setObjectName("EventIamge3")
        self.UserName_10 = QtWidgets.QLabel(HostEventDisplayDialog)
        self.UserName_10.setGeometry(QtCore.QRect(10, 260, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.UserName_10.setFont(font)
        self.UserName_10.setStyleSheet("border-image: \\*url();")
        self.UserName_10.setObjectName("UserName_10")
        self.DateOutput = QtWidgets.QLabel(HostEventDisplayDialog)
        self.DateOutput.setGeometry(QtCore.QRect(340, 220, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.DateOutput.setFont(font)
        self.DateOutput.setStyleSheet("border-image: \\*url();")
        self.DateOutput.setObjectName("DateOutput")
        self.UserName_3 = QtWidgets.QLabel(HostEventDisplayDialog)
        self.UserName_3.setGeometry(QtCore.QRect(10, 180, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.UserName_3.setFont(font)
        self.UserName_3.setStyleSheet("border-image: \\*url();")
        self.UserName_3.setObjectName("UserName_3")
        self.graphicsView = QtWidgets.QGraphicsView(HostEventDisplayDialog)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 745, 453))
        self.graphicsView.setStyleSheet("border-image: url(./bg.png)\n"
"\n"
"")
        self.graphicsView.setObjectName("graphicsView")
        self.GroupEmailContent = QtWidgets.QTextEdit(HostEventDisplayDialog)
        self.GroupEmailContent.setGeometry(QtCore.QRect(11, 368, 501, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.GroupEmailContent.setFont(font)
        self.GroupEmailContent.setAutoFillBackground(False)
        self.GroupEmailContent.setStyleSheet("border-image: \\*url();\n"
"border-radius: 5px;\n"
"")
        self.GroupEmailContent.setObjectName("GroupEmailContent")
        self.BackButton = QtWidgets.QPushButton(HostEventDisplayDialog)
        self.BackButton.setGeometry(QtCore.QRect(606, 33, 81, 34))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BackButton.setFont(font)
        self.BackButton.setStyleSheet("border-image: \\*url();")
        self.BackButton.setObjectName("BackButton")
        self.Attendee4 = QtWidgets.QPushButton(HostEventDisplayDialog)
        self.Attendee4.setGeometry(QtCore.QRect(172, 298, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Attendee4.setFont(font)
        self.Attendee4.setStyleSheet("border-image: url(./DefaultUser.png);\n"
"")
        self.Attendee4.setText("")
        self.Attendee4.setObjectName("Attendee4")
        self.Attendee6 = QtWidgets.QPushButton(HostEventDisplayDialog)
        self.Attendee6.setGeometry(QtCore.QRect(272, 298, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Attendee6.setFont(font)
        self.Attendee6.setStyleSheet("border-image: url(./DefaultUser.png);\n"
"")
        self.Attendee6.setText("")
        self.Attendee6.setObjectName("Attendee6")
        self.Attendee2 = QtWidgets.QPushButton(HostEventDisplayDialog)
        self.Attendee2.setGeometry(QtCore.QRect(72, 298, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Attendee2.setFont(font)
        self.Attendee2.setStyleSheet("border-image: url(./DefaultUser.png);\n"
"")
        self.Attendee2.setText("")
        self.Attendee2.setObjectName("Attendee2")
        self.Attendee7 = QtWidgets.QPushButton(HostEventDisplayDialog)
        self.Attendee7.setGeometry(QtCore.QRect(322, 298, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Attendee7.setFont(font)
        self.Attendee7.setStyleSheet("border-image: url(./DefaultUser.png);\n"
"")
        self.Attendee7.setText("")
        self.Attendee7.setObjectName("Attendee7")
        self.Attendee8 = QtWidgets.QPushButton(HostEventDisplayDialog)
        self.Attendee8.setGeometry(QtCore.QRect(372, 298, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Attendee8.setFont(font)
        self.Attendee8.setStyleSheet("border-image: url(./DefaultUser.png);\n"
"")
        self.Attendee8.setText("")
        self.Attendee8.setObjectName("Attendee8")
        self.Attendee3 = QtWidgets.QPushButton(HostEventDisplayDialog)
        self.Attendee3.setGeometry(QtCore.QRect(122, 298, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Attendee3.setFont(font)
        self.Attendee3.setStyleSheet("border-image: url(./DefaultUser.png);\n"
"")
        self.Attendee3.setText("")
        self.Attendee3.setObjectName("Attendee3")
        self.Attendee9 = QtWidgets.QPushButton(HostEventDisplayDialog)
        self.Attendee9.setGeometry(QtCore.QRect(422, 298, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Attendee9.setFont(font)
        self.Attendee9.setStyleSheet("border-image: url(./DefaultUser.png);\n"
"")
        self.Attendee9.setText("")
        self.Attendee9.setObjectName("Attendee9")
        self.Attendee1 = QtWidgets.QPushButton(HostEventDisplayDialog)
        self.Attendee1.setGeometry(QtCore.QRect(22, 298, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Attendee1.setFont(font)
        self.Attendee1.setStyleSheet("border-image: url(./DefaultUser.png);\n"
"")
        self.Attendee1.setText("")
        self.Attendee1.setObjectName("Attendee1")
        self.Attendee10 = QtWidgets.QPushButton(HostEventDisplayDialog)
        self.Attendee10.setGeometry(QtCore.QRect(472, 298, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Attendee10.setFont(font)
        self.Attendee10.setStyleSheet("border-image: url(./DefaultUser.png);\n"
"")
        self.Attendee10.setText("")
        self.Attendee10.setObjectName("Attendee10")
        self.Attendee5 = QtWidgets.QPushButton(HostEventDisplayDialog)
        self.Attendee5.setGeometry(QtCore.QRect(222, 298, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Attendee5.setFont(font)
        self.Attendee5.setStyleSheet("border-image: url(./DefaultUser.png);\n"
"")
        self.Attendee5.setText("")
        self.Attendee5.setObjectName("Attendee5")
        self.HostImage = QtWidgets.QPushButton(HostEventDisplayDialog)
        self.HostImage.setGeometry(QtCore.QRect(210, 213, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.HostImage.setFont(font)
        self.HostImage.setStyleSheet("border-image: url(./DefaultUser.png);\n"
"")
        self.HostImage.setText("")
        self.HostImage.setObjectName("HostImage")
        self.TokenInput = QtWidgets.QLineEdit(HostEventDisplayDialog)
        self.TokenInput.setGeometry(QtCore.QRect(120, 340, 391, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.TokenInput.setFont(font)
        self.TokenInput.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.TokenInput.setStyleSheet("border-image: \\*url();\n"
"border-radius: 5px;\n"
"")
        self.TokenInput.setText("")
        self.TokenInput.setClearButtonEnabled(False)
        self.TokenInput.setObjectName("TokenInput")
        self.EventEditButton_2 = QtWidgets.QPushButton(HostEventDisplayDialog)
        self.EventEditButton_2.setGeometry(QtCore.QRect(90, 254, 171, 34))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EventEditButton_2.setFont(font)
        self.EventEditButton_2.setStyleSheet("border-image: \\*url();")
        self.EventEditButton_2.setObjectName("EventEditButton_2")

        
        
        
        
        
        
        
        
        self.graphicsView.raise_()
        self.UserName_13.raise_()
        self.UserName_8.raise_()
        self.HostIDOutput.raise_()
        self.line_2.raise_()
        self.DescriptionOutput.raise_()
        self.graphicsView_14.raise_()
        self.UserName_5.raise_()
        self.EventEditButton.raise_()
        self.AddressOutput.raise_()
        self.CityOutput.raise_()
        self.label_2.raise_()
        self.UserName.raise_()
        self.EventIamge1.raise_()
        self.EventIamge2.raise_()
        self.line_3.raise_()
        self.UserName_12.raise_()
        self.UserName_9.raise_()
        self.UserName_11.raise_()
        self.SendEmailButton.raise_()
        self.UserName_2.raise_()
        self.EventIamge3.raise_()
        self.UserName_10.raise_()
        self.DateOutput.raise_()
        self.UserName_3.raise_()
        self.GroupEmailContent.raise_()
        self.BackButton.raise_()
        self.Attendee4.raise_()
        self.Attendee6.raise_()
        self.Attendee2.raise_()
        self.Attendee7.raise_()
        self.Attendee8.raise_()
        self.Attendee3.raise_()
        self.Attendee9.raise_()
        self.Attendee1.raise_()
        self.Attendee10.raise_()
        self.Attendee5.raise_()
        self.HostImage.raise_()
        self.TokenInput.raise_()
        self.EventEditButton_2.raise_()


        self.retranslateUi(HostEventDisplayDialog)
        QtCore.QMetaObject.connectSlotsByName(HostEventDisplayDialog)

    def retranslateUi(self, HostEventDisplayDialog):
        _translate = QtCore.QCoreApplication.translate
        HostEventDisplayDialog.setWindowTitle(_translate("HostEventDisplayDialog", "Dialog"))
        self.UserName_13.setText(_translate("HostEventDisplayDialog", "map"))
        self.UserName_8.setText(_translate("HostEventDisplayDialog", "Host"))
        self.HostIDOutput.setText(_translate("HostEventDisplayDialog", "I\'m Host Nickname"))
        self.DescriptionOutput.setText(_translate("HostEventDisplayDialog", "I\'m a description. I\'m a description. I\'m a description. I\'m a description. I\'m a description. I\'m a description. "))
        self.UserName_5.setText(_translate("HostEventDisplayDialog", "City"))
        self.EventEditButton.setText(_translate("HostEventDisplayDialog", "Edit"))
        self.AddressOutput.setText(_translate("HostEventDisplayDialog", "I\'m address I\'m address"))
        self.CityOutput.setText(_translate("HostEventDisplayDialog", "I\'m city I\'m city"))
        self.label_2.setText(_translate("HostEventDisplayDialog", "JoinMe"))
        self.UserName.setText(_translate("HostEventDisplayDialog", "Title of the event"))
        self.UserName_12.setText(_translate("HostEventDisplayDialog", "Images"))
        self.UserName_9.setText(_translate("HostEventDisplayDialog", "Date"))
        self.UserName_11.setText(_translate("HostEventDisplayDialog", "Group Email"))
        self.SendEmailButton.setText(_translate("HostEventDisplayDialog", "Send"))
        self.UserName_2.setText(_translate("HostEventDisplayDialog", "Description"))
        self.UserName_10.setText(_translate("HostEventDisplayDialog", "Attendee"))
        self.DateOutput.setText(_translate("HostEventDisplayDialog", "I\'m Date I\'m Date"))
        self.UserName_3.setText(_translate("HostEventDisplayDialog", "Address"))
        self.GroupEmailContent.setWhatsThis(_translate("HostEventDisplayDialog", "ddd"))
        self.GroupEmailContent.setPlaceholderText(_translate("HostEventDisplayDialog", "Please input your email content..."))
        self.BackButton.setText(_translate("HostEventDisplayDialog", "Back"))
        self.TokenInput.setPlaceholderText(_translate("HostEventDisplayDialog", "Please input the user nickname if needed."))
        self.EventEditButton_2.setText(_translate("HostEventDisplayDialog", "Extract Information"))

