# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hosteventdisplaydialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HostEventDisplayDialog(object):
    def setupUi(self, HostEventDisplayDialog):
        HostEventDisplayDialog.setObjectName("HostEventDisplayDialog")
        HostEventDisplayDialog.resize(745, 453)
        HostEventDisplayDialog.setStyleSheet("border-image: url(./bg.png)")
        self.AttendImage2 = QtWidgets.QGraphicsView(HostEventDisplayDialog)
        self.AttendImage2.setGeometry(QtCore.QRect(90, 300, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendImage2.setFont(font)
        self.AttendImage2.setStyleSheet("\n"
"border-radius: 15px;")
        self.AttendImage2.setObjectName("AttendImage2")
        self.AttendImage3 = QtWidgets.QGraphicsView(HostEventDisplayDialog)
        self.AttendImage3.setGeometry(QtCore.QRect(140, 300, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendImage3.setFont(font)
        self.AttendImage3.setStyleSheet("\n"
"border-radius: 15px;")
        self.AttendImage3.setObjectName("AttendImage3")
        self.AttendImage5 = QtWidgets.QGraphicsView(HostEventDisplayDialog)
        self.AttendImage5.setGeometry(QtCore.QRect(240, 300, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendImage5.setFont(font)
        self.AttendImage5.setStyleSheet("\n"
"border-radius: 15px;")
        self.AttendImage5.setObjectName("AttendImage5")
        self.UserName_13 = QtWidgets.QLabel(HostEventDisplayDialog)
        self.UserName_13.setGeometry(QtCore.QRect(630, 380, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.UserName_13.setFont(font)
        self.UserName_13.setStyleSheet("border-image: \\*url();")
        self.UserName_13.setObjectName("UserName_13")
        self.UserName_8 = QtWidgets.QLabel(HostEventDisplayDialog)
        self.UserName_8.setGeometry(QtCore.QRect(10, 220, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.UserName_8.setFont(font)
        self.UserName_8.setStyleSheet("border-image: \\*url();")
        self.UserName_8.setObjectName("UserName_8")
        self.HostIDOutput = QtWidgets.QLabel(HostEventDisplayDialog)
        self.HostIDOutput.setGeometry(QtCore.QRect(60, 220, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.HostIDOutput.setFont(font)
        self.HostIDOutput.setStyleSheet("border-image: \\*url();")
        self.HostIDOutput.setObjectName("HostIDOutput")
        self.line_2 = QtWidgets.QFrame(HostEventDisplayDialog)
        self.line_2.setGeometry(QtCore.QRect(0, 50, 600, 2))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line_2.setFont(font)
        self.line_2.setStyleSheet("border-image: \\*url();\n"
"background-color: rgb(19, 35, 255);\n"
"")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.DescriptionOutput = QtWidgets.QLabel(HostEventDisplayDialog)
        self.DescriptionOutput.setGeometry(QtCore.QRect(10, 120, 551, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.DescriptionOutput.setFont(font)
        self.DescriptionOutput.setStyleSheet("border-image: \\*url();")
        self.DescriptionOutput.setObjectName("DescriptionOutput")
        self.graphicsView_14 = QtWidgets.QGraphicsView(HostEventDisplayDialog)
        self.graphicsView_14.setGeometry(QtCore.QRect(630, 402, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.graphicsView_14.setFont(font)
        self.graphicsView_14.setStyleSheet("border-image: url(:/pin-2.png)")
        self.graphicsView_14.setObjectName("graphicsView_14")
        self.UserName_5 = QtWidgets.QLabel(HostEventDisplayDialog)
        self.UserName_5.setGeometry(QtCore.QRect(300, 180, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.UserName_5.setFont(font)
        self.UserName_5.setStyleSheet("border-image: \\*url();")
        self.UserName_5.setObjectName("UserName_5")
        self.AttendEventButton = QtWidgets.QPushButton(HostEventDisplayDialog)
        self.AttendEventButton.setGeometry(QtCore.QRect(608, 50, 81, 34))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendEventButton.setFont(font)
        self.AttendEventButton.setStyleSheet("border-image: \\*url();")
        self.AttendEventButton.setObjectName("AttendEventButton")
        self.AddressOutput = QtWidgets.QLabel(HostEventDisplayDialog)
        self.AddressOutput.setGeometry(QtCore.QRect(90, 180, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AddressOutput.setFont(font)
        self.AddressOutput.setStyleSheet("border-image: \\*url();")
        self.AddressOutput.setObjectName("AddressOutput")
        self.CityOutput = QtWidgets.QLabel(HostEventDisplayDialog)
        self.CityOutput.setGeometry(QtCore.QRect(340, 180, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.CityOutput.setFont(font)
        self.CityOutput.setStyleSheet("border-image: \\*url();")
        self.CityOutput.setObjectName("CityOutput")
        self.label_2 = QtWidgets.QLabel(HostEventDisplayDialog)
        self.label_2.setGeometry(QtCore.QRect(8, 3, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        font.setPointSize(34)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-image: \\*url();")
        self.label_2.setObjectName("label_2")
        self.UserName = QtWidgets.QLabel(HostEventDisplayDialog)
        self.UserName.setGeometry(QtCore.QRect(8, 55, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.UserName.setFont(font)
        self.UserName.setStyleSheet("border-image: \\*url();")
        self.UserName.setObjectName("UserName")
        self.AttendImage8 = QtWidgets.QGraphicsView(HostEventDisplayDialog)
        self.AttendImage8.setGeometry(QtCore.QRect(390, 300, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendImage8.setFont(font)
        self.AttendImage8.setStyleSheet("\n"
"border-radius: 15px;")
        self.AttendImage8.setObjectName("AttendImage8")
        self.EventIamge1 = QtWidgets.QGraphicsView(HostEventDisplayDialog)
        self.EventIamge1.setGeometry(QtCore.QRect(580, 112, 131, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EventIamge1.setFont(font)
        self.EventIamge1.setStyleSheet("")
        self.EventIamge1.setObjectName("EventIamge1")
        self.EventIamge1_2 = QtWidgets.QGraphicsView(HostEventDisplayDialog)
        self.EventIamge1_2.setGeometry(QtCore.QRect(580, 200, 131, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EventIamge1_2.setFont(font)
        self.EventIamge1_2.setStyleSheet("")
        self.EventIamge1_2.setObjectName("EventIamge1_2")
        self.line_3 = QtWidgets.QFrame(HostEventDisplayDialog)
        self.line_3.setGeometry(QtCore.QRect(0, 80, 600, 2))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line_3.setFont(font)
        self.line_3.setStyleSheet("border-image: \\*url();\n"
"background-color: rgb(19, 35, 255);\n"
"")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.UserName_12 = QtWidgets.QLabel(HostEventDisplayDialog)
        self.UserName_12.setGeometry(QtCore.QRect(620, 90, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.UserName_12.setFont(font)
        self.UserName_12.setStyleSheet("border-image: \\*url();")
        self.UserName_12.setObjectName("UserName_12")
        self.UserName_9 = QtWidgets.QLabel(HostEventDisplayDialog)
        self.UserName_9.setGeometry(QtCore.QRect(300, 220, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.UserName_9.setFont(font)
        self.UserName_9.setStyleSheet("border-image: \\*url();")
        self.UserName_9.setObjectName("UserName_9")
        self.AttendImage1 = QtWidgets.QGraphicsView(HostEventDisplayDialog)
        self.AttendImage1.setGeometry(QtCore.QRect(40, 300, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendImage1.setFont(font)
        self.AttendImage1.setStyleSheet("\n"
"border-radius: 15px;")
        self.AttendImage1.setObjectName("AttendImage1")
        self.AttendImage6 = QtWidgets.QGraphicsView(HostEventDisplayDialog)
        self.AttendImage6.setGeometry(QtCore.QRect(190, 300, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendImage6.setFont(font)
        self.AttendImage6.setStyleSheet("\n"
"border-radius: 15px;")
        self.AttendImage6.setObjectName("AttendImage6")
        self.AttendImage7 = QtWidgets.QGraphicsView(HostEventDisplayDialog)
        self.AttendImage7.setGeometry(QtCore.QRect(340, 300, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendImage7.setFont(font)
        self.AttendImage7.setStyleSheet("\n"
"border-radius: 15px;")
        self.AttendImage7.setObjectName("AttendImage7")
        self.UserName_11 = QtWidgets.QLabel(HostEventDisplayDialog)
        self.UserName_11.setGeometry(QtCore.QRect(10, 340, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.UserName_11.setFont(font)
        self.UserName_11.setStyleSheet("border-image: \\*url();")
        self.UserName_11.setObjectName("UserName_11")
        self.AttendImage9 = QtWidgets.QGraphicsView(HostEventDisplayDialog)
        self.AttendImage9.setGeometry(QtCore.QRect(440, 300, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendImage9.setFont(font)
        self.AttendImage9.setStyleSheet("\n"
"border-radius: 15px;")
        self.AttendImage9.setObjectName("AttendImage9")
        self.SendEmailButton = QtWidgets.QPushButton(HostEventDisplayDialog)
        self.SendEmailButton.setGeometry(QtCore.QRect(510, 390, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.SendEmailButton.setFont(font)
        self.SendEmailButton.setStyleSheet("border-image: \\*url();")
        self.SendEmailButton.setObjectName("SendEmailButton")
        self.UserName_2 = QtWidgets.QLabel(HostEventDisplayDialog)
        self.UserName_2.setGeometry(QtCore.QRect(9, 90, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.UserName_2.setFont(font)
        self.UserName_2.setStyleSheet("border-image: \\*url();")
        self.UserName_2.setObjectName("UserName_2")
        self.EmailContentInput = QtWidgets.QLineEdit(HostEventDisplayDialog)
        self.EmailContentInput.setGeometry(QtCore.QRect(10, 370, 501, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.EmailContentInput.setFont(font)
        self.EmailContentInput.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.EmailContentInput.setStyleSheet("border-image: \\*url();\n"
"border-radius: 5px;\n"
"")
        self.EmailContentInput.setText("")
        self.EmailContentInput.setClearButtonEnabled(False)
        self.EmailContentInput.setObjectName("EmailContentInput")
        self.EventIamge3 = QtWidgets.QGraphicsView(HostEventDisplayDialog)
        self.EventIamge3.setGeometry(QtCore.QRect(580, 290, 131, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EventIamge3.setFont(font)
        self.EventIamge3.setStyleSheet("")
        self.EventIamge3.setObjectName("EventIamge3")
        self.UserName_10 = QtWidgets.QLabel(HostEventDisplayDialog)
        self.UserName_10.setGeometry(QtCore.QRect(10, 260, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.UserName_10.setFont(font)
        self.UserName_10.setStyleSheet("border-image: \\*url();")
        self.UserName_10.setObjectName("UserName_10")
        self.AttendImage4 = QtWidgets.QGraphicsView(HostEventDisplayDialog)
        self.AttendImage4.setGeometry(QtCore.QRect(290, 300, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendImage4.setFont(font)
        self.AttendImage4.setStyleSheet("\n"
"border-radius: 15px;")
        self.AttendImage4.setObjectName("AttendImage4")
        self.CityOutput_2 = QtWidgets.QLabel(HostEventDisplayDialog)
        self.CityOutput_2.setGeometry(QtCore.QRect(340, 220, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.CityOutput_2.setFont(font)
        self.CityOutput_2.setStyleSheet("border-image: \\*url();")
        self.CityOutput_2.setObjectName("CityOutput_2")
        self.UserName_3 = QtWidgets.QLabel(HostEventDisplayDialog)
        self.UserName_3.setGeometry(QtCore.QRect(10, 180, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.UserName_3.setFont(font)
        self.UserName_3.setStyleSheet("border-image: \\*url();")
        self.UserName_3.setObjectName("UserName_3")
        self.AttendImage10 = QtWidgets.QGraphicsView(HostEventDisplayDialog)
        self.AttendImage10.setGeometry(QtCore.QRect(490, 300, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendImage10.setFont(font)
        self.AttendImage10.setStyleSheet("\n"
"border-radius: 15px;")
        self.AttendImage10.setObjectName("AttendImage10")
        self.RemoveUser = QtWidgets.QPushButton(HostEventDisplayDialog)
        self.RemoveUser.setGeometry(QtCore.QRect(180, 257, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.RemoveUser.setFont(font)
        self.RemoveUser.setStyleSheet("border-image: \\*url();")
        self.RemoveUser.setObjectName("RemoveUser")
        self.UserID = QtWidgets.QLineEdit(HostEventDisplayDialog)
        self.UserID.setGeometry(QtCore.QRect(100, 260, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.UserID.setFont(font)
        self.UserID.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.UserID.setStyleSheet("border-image: \\*url();\n"
"border-radius: 5px;\n"
"")
        self.UserID.setText("")
        self.UserID.setClearButtonEnabled(False)
        self.UserID.setObjectName("UserID")

        self.retranslateUi(HostEventDisplayDialog)
        QtCore.QMetaObject.connectSlotsByName(HostEventDisplayDialog)

    def retranslateUi(self, HostEventDisplayDialog):
        _translate = QtCore.QCoreApplication.translate
        HostEventDisplayDialog.setWindowTitle(_translate("HostEventDisplayDialog", "Dialog"))
        self.UserName_13.setText(_translate("HostEventDisplayDialog", "map"))
        self.UserName_8.setText(_translate("HostEventDisplayDialog", "Host"))
        self.HostIDOutput.setText(_translate("HostEventDisplayDialog", "I\'m Host Nickname"))
        self.DescriptionOutput.setText(_translate("HostEventDisplayDialog", "I\'m a description. I\'m a description. I\'m a description. I\'m a description. I\'m a description. I\'m a description. "))
        self.UserName_5.setText(_translate("HostEventDisplayDialog", "City"))
        self.AttendEventButton.setText(_translate("HostEventDisplayDialog", "Edit"))
        self.AddressOutput.setText(_translate("HostEventDisplayDialog", "I\'m address I\'m address"))
        self.CityOutput.setText(_translate("HostEventDisplayDialog", "I\'m city I\'m city"))
        self.label_2.setText(_translate("HostEventDisplayDialog", "JoinMe"))
        self.UserName.setText(_translate("HostEventDisplayDialog", "Title of the event"))
        self.UserName_12.setText(_translate("HostEventDisplayDialog", "Images"))
        self.UserName_9.setText(_translate("HostEventDisplayDialog", "Date"))
        self.UserName_11.setText(_translate("HostEventDisplayDialog", "Group Email"))
        self.SendEmailButton.setText(_translate("HostEventDisplayDialog", "Send"))
        self.UserName_2.setText(_translate("HostEventDisplayDialog", "Description"))
        self.UserName_10.setText(_translate("HostEventDisplayDialog", "Attendee"))
        self.CityOutput_2.setText(_translate("HostEventDisplayDialog", "I\'m Date I\'m Date"))
        self.UserName_3.setText(_translate("HostEventDisplayDialog", "Address"))
        self.RemoveUser.setText(_translate("HostEventDisplayDialog", "Remove"))

