# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hosteventedit.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HostEventEdit(object):
    def setupUi(self, HostEventEdit):
        HostEventEdit.setObjectName("HostEventEdit")
        HostEventEdit.resize(765, 453)
        HostEventEdit.setStyleSheet("border-image: url(./bg.png)")
        self.AttendImage2 = QtWidgets.QGraphicsView(HostEventEdit)
        self.AttendImage2.setGeometry(QtCore.QRect(189, 277, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendImage2.setFont(font)
        self.AttendImage2.setStyleSheet("\n"
"border-radius: 15px;")
        self.AttendImage2.setObjectName("AttendImage2")
        self.AttendImage3 = QtWidgets.QGraphicsView(HostEventEdit)
        self.AttendImage3.setGeometry(QtCore.QRect(239, 277, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendImage3.setFont(font)
        self.AttendImage3.setStyleSheet("\n"
"border-radius: 15px;")
        self.AttendImage3.setObjectName("AttendImage3")
        self.AttendImage5 = QtWidgets.QGraphicsView(HostEventEdit)
        self.AttendImage5.setGeometry(QtCore.QRect(339, 277, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendImage5.setFont(font)
        self.AttendImage5.setStyleSheet("\n"
"border-radius: 15px;")
        self.AttendImage5.setObjectName("AttendImage5")
        self.line_2 = QtWidgets.QFrame(HostEventEdit)
        self.line_2.setGeometry(QtCore.QRect(0, 47, 640, 2))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line_2.setFont(font)
        self.line_2.setStyleSheet("border-image: \\*url();\n"
"background-color: rgb(19, 35, 255);\n"
"")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.UserName_5 = QtWidgets.QLabel(HostEventEdit)
        self.UserName_5.setGeometry(QtCore.QRect(430, 170, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.UserName_5.setFont(font)
        self.UserName_5.setStyleSheet("border-image: \\*url();")
        self.UserName_5.setObjectName("UserName_5")
        self.EditEventButton = QtWidgets.QPushButton(HostEventEdit)
        self.EditEventButton.setGeometry(QtCore.QRect(651, 46, 81, 34))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EditEventButton.setFont(font)
        self.EditEventButton.setStyleSheet("border-image: \\*url();")
        self.EditEventButton.setObjectName("EditEventButton")
        self.label_2 = QtWidgets.QLabel(HostEventEdit)
        self.label_2.setGeometry(QtCore.QRect(8, 0, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        font.setPointSize(34)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-image: \\*url();")
        self.label_2.setObjectName("label_2")
        self.UserName = QtWidgets.QLabel(HostEventEdit)
        self.UserName.setGeometry(QtCore.QRect(8, 52, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.UserName.setFont(font)
        self.UserName.setStyleSheet("border-image: \\*url();")
        self.UserName.setObjectName("UserName")
        self.AttendImage8 = QtWidgets.QGraphicsView(HostEventEdit)
        self.AttendImage8.setGeometry(QtCore.QRect(489, 277, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendImage8.setFont(font)
        self.AttendImage8.setStyleSheet("\n"
"border-radius: 15px;")
        self.AttendImage8.setObjectName("AttendImage8")
        self.EventIamge1 = QtWidgets.QGraphicsView(HostEventEdit)
        self.EventIamge1.setGeometry(QtCore.QRect(97, 340, 131, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EventIamge1.setFont(font)
        self.EventIamge1.setStyleSheet("")
        self.EventIamge1.setObjectName("EventIamge1")
        self.EventIamge1_2 = QtWidgets.QGraphicsView(HostEventEdit)
        self.EventIamge1_2.setGeometry(QtCore.QRect(317, 340, 131, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EventIamge1_2.setFont(font)
        self.EventIamge1_2.setStyleSheet("")
        self.EventIamge1_2.setObjectName("EventIamge1_2")
        self.line_3 = QtWidgets.QFrame(HostEventEdit)
        self.line_3.setGeometry(QtCore.QRect(0, 77, 640, 2))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line_3.setFont(font)
        self.line_3.setStyleSheet("border-image: \\*url();\n"
"background-color: rgb(19, 35, 255);\n"
"")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.UserName_12 = QtWidgets.QLabel(HostEventEdit)
        self.UserName_12.setGeometry(QtCore.QRect(50, 310, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.UserName_12.setFont(font)
        self.UserName_12.setStyleSheet("border-image: \\*url();")
        self.UserName_12.setObjectName("UserName_12")
        self.AttendImage1 = QtWidgets.QGraphicsView(HostEventEdit)
        self.AttendImage1.setGeometry(QtCore.QRect(139, 277, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendImage1.setFont(font)
        self.AttendImage1.setStyleSheet("\n"
"border-radius: 15px;")
        self.AttendImage1.setObjectName("AttendImage1")
        self.AttendImage6 = QtWidgets.QGraphicsView(HostEventEdit)
        self.AttendImage6.setGeometry(QtCore.QRect(289, 277, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendImage6.setFont(font)
        self.AttendImage6.setStyleSheet("\n"
"border-radius: 15px;")
        self.AttendImage6.setObjectName("AttendImage6")
        self.AttendImage7 = QtWidgets.QGraphicsView(HostEventEdit)
        self.AttendImage7.setGeometry(QtCore.QRect(439, 277, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendImage7.setFont(font)
        self.AttendImage7.setStyleSheet("\n"
"border-radius: 15px;")
        self.AttendImage7.setObjectName("AttendImage7")
        self.AttendImage9 = QtWidgets.QGraphicsView(HostEventEdit)
        self.AttendImage9.setGeometry(QtCore.QRect(539, 277, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendImage9.setFont(font)
        self.AttendImage9.setStyleSheet("\n"
"border-radius: 15px;")
        self.AttendImage9.setObjectName("AttendImage9")
        self.UserName_2 = QtWidgets.QLabel(HostEventEdit)
        self.UserName_2.setGeometry(QtCore.QRect(49, 80, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.UserName_2.setFont(font)
        self.UserName_2.setStyleSheet("border-image: \\*url();")
        self.UserName_2.setObjectName("UserName_2")
        self.EventIamge3 = QtWidgets.QGraphicsView(HostEventEdit)
        self.EventIamge3.setGeometry(QtCore.QRect(527, 340, 131, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EventIamge3.setFont(font)
        self.EventIamge3.setStyleSheet("")
        self.EventIamge3.setObjectName("EventIamge3")
        self.UserName_10 = QtWidgets.QLabel(HostEventEdit)
        self.UserName_10.setGeometry(QtCore.QRect(50, 250, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.UserName_10.setFont(font)
        self.UserName_10.setStyleSheet("border-image: \\*url();")
        self.UserName_10.setObjectName("UserName_10")
        self.AttendImage4 = QtWidgets.QGraphicsView(HostEventEdit)
        self.AttendImage4.setGeometry(QtCore.QRect(389, 277, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendImage4.setFont(font)
        self.AttendImage4.setStyleSheet("\n"
"border-radius: 15px;")
        self.AttendImage4.setObjectName("AttendImage4")
        self.UserName_3 = QtWidgets.QLabel(HostEventEdit)
        self.UserName_3.setGeometry(QtCore.QRect(50, 170, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.UserName_3.setFont(font)
        self.UserName_3.setStyleSheet("border-image: \\*url();")
        self.UserName_3.setObjectName("UserName_3")
        self.AttendImage10 = QtWidgets.QGraphicsView(HostEventEdit)
        self.AttendImage10.setGeometry(QtCore.QRect(589, 277, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendImage10.setFont(font)
        self.AttendImage10.setStyleSheet("\n"
"border-radius: 15px;")
        self.AttendImage10.setObjectName("AttendImage10")
        self.EmailContentInput_2 = QtWidgets.QLineEdit(HostEventEdit)
        self.EmailContentInput_2.setGeometry(QtCore.QRect(50, 103, 661, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.EmailContentInput_2.setFont(font)
        self.EmailContentInput_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.EmailContentInput_2.setStyleSheet("border-image: \\*url();\n"
"border-radius: 5px;\n"
"")
        self.EmailContentInput_2.setText("")
        self.EmailContentInput_2.setClearButtonEnabled(False)
        self.EmailContentInput_2.setObjectName("EmailContentInput_2")
        self.EmailContentInput_3 = QtWidgets.QLineEdit(HostEventEdit)
        self.EmailContentInput_3.setGeometry(QtCore.QRect(120, 170, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.EmailContentInput_3.setFont(font)
        self.EmailContentInput_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.EmailContentInput_3.setStyleSheet("border-image: \\*url();\n"
"border-radius: 5px;\n"
"")
        self.EmailContentInput_3.setText("")
        self.EmailContentInput_3.setClearButtonEnabled(False)
        self.EmailContentInput_3.setObjectName("EmailContentInput_3")
        self.EmailContentInput_4 = QtWidgets.QLineEdit(HostEventEdit)
        self.EmailContentInput_4.setGeometry(QtCore.QRect(470, 170, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.EmailContentInput_4.setFont(font)
        self.EmailContentInput_4.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.EmailContentInput_4.setStyleSheet("border-image: \\*url();\n"
"border-radius: 5px;\n"
"")
        self.EmailContentInput_4.setText("")
        self.EmailContentInput_4.setClearButtonEnabled(False)
        self.EmailContentInput_4.setObjectName("EmailContentInput_4")
        self.EmailContentInput_5 = QtWidgets.QLineEdit(HostEventEdit)
        self.EmailContentInput_5.setGeometry(QtCore.QRect(50, 53, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.EmailContentInput_5.setFont(font)
        self.EmailContentInput_5.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.EmailContentInput_5.setStyleSheet("border-image: \\*url();\n"
"border-radius: 5px;\n"
"")
        self.EmailContentInput_5.setText("")
        self.EmailContentInput_5.setClearButtonEnabled(False)
        self.EmailContentInput_5.setObjectName("EmailContentInput_5")
        self.EditEventButton_2 = QtWidgets.QPushButton(HostEventEdit)
        self.EditEventButton_2.setGeometry(QtCore.QRect(117, 420, 81, 34))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EditEventButton_2.setFont(font)
        self.EditEventButton_2.setStyleSheet("border-image: \\*url();")
        self.EditEventButton_2.setObjectName("EditEventButton_2")
        self.EditEventButton_3 = QtWidgets.QPushButton(HostEventEdit)
        self.EditEventButton_3.setGeometry(QtCore.QRect(347, 420, 81, 34))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EditEventButton_3.setFont(font)
        self.EditEventButton_3.setStyleSheet("border-image: \\*url();")
        self.EditEventButton_3.setObjectName("EditEventButton_3")
        self.EditEventButton_4 = QtWidgets.QPushButton(HostEventEdit)
        self.EditEventButton_4.setGeometry(QtCore.QRect(557, 420, 81, 34))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EditEventButton_4.setFont(font)
        self.EditEventButton_4.setStyleSheet("border-image: \\*url();")
        self.EditEventButton_4.setObjectName("EditEventButton_4")
        self.UserName_4 = QtWidgets.QLabel(HostEventEdit)
        self.UserName_4.setGeometry(QtCore.QRect(50, 196, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.UserName_4.setFont(font)
        self.UserName_4.setStyleSheet("border-image: \\*url();")
        self.UserName_4.setObjectName("UserName_4")
        self.UserName_6 = QtWidgets.QLabel(HostEventEdit)
        self.UserName_6.setGeometry(QtCore.QRect(50, 222, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.UserName_6.setFont(font)
        self.UserName_6.setStyleSheet("border-image: \\*url();")
        self.UserName_6.setObjectName("UserName_6")
        self.UserName_7 = QtWidgets.QLabel(HostEventEdit)
        self.UserName_7.setGeometry(QtCore.QRect(410, 222, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.UserName_7.setFont(font)
        self.UserName_7.setStyleSheet("border-image: \\*url();")
        self.UserName_7.setObjectName("UserName_7")
        self.EmailContentInput_6 = QtWidgets.QLineEdit(HostEventEdit)
        self.EmailContentInput_6.setGeometry(QtCore.QRect(510, 221, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.EmailContentInput_6.setFont(font)
        self.EmailContentInput_6.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.EmailContentInput_6.setStyleSheet("border-image: \\*url();\n"
"border-radius: 5px;\n"
"")
        self.EmailContentInput_6.setText("")
        self.EmailContentInput_6.setClearButtonEnabled(False)
        self.EmailContentInput_6.setObjectName("EmailContentInput_6")
        self.TimeComboBox = QtWidgets.QComboBox(HostEventEdit)
        self.TimeComboBox.setGeometry(QtCore.QRect(140, 220, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.TimeComboBox.setFont(font)
        self.TimeComboBox.setStyleSheet("border-image: \\*url();")
        self.TimeComboBox.setEditable(False)
        self.TimeComboBox.setObjectName("TimeComboBox")
        self.TimeComboBox.addItem("")
        self.TimeComboBox.addItem("")
        self.TimeComboBox.addItem("")
        self.TimeComboBox.addItem("")
        self.TimeComboBox.addItem("")
        self.TimeComboBox.addItem("")
        self.TimeComboBox.addItem("")
        self.TimeComboBox.addItem("")
        self.TimeComboBox.addItem("")
        self.TimeComboBox.addItem("")
        self.TimeComboBox.addItem("")
        self.TimeComboBox.addItem("")
        self.TimeComboBox_2 = QtWidgets.QComboBox(HostEventEdit)
        self.TimeComboBox_2.setGeometry(QtCore.QRect(220, 220, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.TimeComboBox_2.setFont(font)
        self.TimeComboBox_2.setStyleSheet("border-image: \\*url();")
        self.TimeComboBox_2.setEditable(False)
        self.TimeComboBox_2.setObjectName("TimeComboBox_2")
        self.TimeComboBox_2.addItem("")
        self.TimeComboBox_2.addItem("")
        self.TimeComboBox_2.addItem("")
        self.TimeComboBox_2.addItem("")
        self.TimeComboBox_2.addItem("")
        self.TimeComboBox_2.addItem("")
        self.TimeComboBox_2.addItem("")
        self.TimeComboBox_2.addItem("")
        self.TimeComboBox_2.addItem("")
        self.TimeComboBox_2.addItem("")
        self.TimeComboBox_2.addItem("")
        self.TimeComboBox_2.addItem("")
        self.TimeComboBox_2.addItem("")
        self.TimeComboBox_3 = QtWidgets.QComboBox(HostEventEdit)
        self.TimeComboBox_3.setGeometry(QtCore.QRect(310, 220, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.TimeComboBox_3.setFont(font)
        self.TimeComboBox_3.setStyleSheet("border-image: \\*url();")
        self.TimeComboBox_3.setEditable(False)
        self.TimeComboBox_3.setObjectName("TimeComboBox_3")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.TimeComboBox_3.addItem("")
        self.CatagoryComboBox = QtWidgets.QComboBox(HostEventEdit)
        self.CatagoryComboBox.setGeometry(QtCore.QRect(90, 194, 131, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.CatagoryComboBox.setFont(font)
        self.CatagoryComboBox.setStyleSheet("border-image: \\*url();")
        self.CatagoryComboBox.setEditable(False)
        self.CatagoryComboBox.setObjectName("CatagoryComboBox")
        self.CatagoryComboBox.addItem("")
        self.CatagoryComboBox.addItem("")
        self.CatagoryComboBox.addItem("")
        self.CatagoryComboBox.addItem("")
        self.CatagoryComboBox.addItem("")
        self.CatagoryComboBox.addItem("")
        self.CatagoryComboBox.addItem("")
        self.CatagoryComboBox.addItem("")
        self.CatagoryComboBox.addItem("")
        self.CatagoryComboBox.addItem("")
        self.CatagoryComboBox.addItem("")

        self.retranslateUi(HostEventEdit)
        QtCore.QMetaObject.connectSlotsByName(HostEventEdit)

    def retranslateUi(self, HostEventEdit):
        _translate = QtCore.QCoreApplication.translate
        HostEventEdit.setWindowTitle(_translate("HostEventEdit", "Dialog"))
        self.UserName_5.setText(_translate("HostEventEdit", "City"))
        self.EditEventButton.setText(_translate("HostEventEdit", "Save"))
        self.label_2.setText(_translate("HostEventEdit", "JoinMe"))
        self.UserName.setText(_translate("HostEventEdit", "Title"))
        self.UserName_12.setText(_translate("HostEventEdit", "Images"))
        self.UserName_2.setText(_translate("HostEventEdit", "Description"))
        self.UserName_10.setText(_translate("HostEventEdit", "Attendee"))
        self.UserName_3.setText(_translate("HostEventEdit", "Address"))
        self.EditEventButton_2.setText(_translate("HostEventEdit", "Upload"))
        self.EditEventButton_3.setText(_translate("HostEventEdit", "Upload"))
        self.EditEventButton_4.setText(_translate("HostEventEdit", "Upload"))
        self.UserName_4.setText(_translate("HostEventEdit", "Tags"))
        self.UserName_6.setText(_translate("HostEventEdit", "Event Date"))
        self.UserName_7.setText(_translate("HostEventEdit", "Time Period"))
        self.TimeComboBox.setItemText(0, _translate("HostEventEdit", "Year"))
        self.TimeComboBox.setItemText(1, _translate("HostEventEdit", "2018"))
        self.TimeComboBox.setItemText(2, _translate("HostEventEdit", "2019"))
        self.TimeComboBox.setItemText(3, _translate("HostEventEdit", "2020"))
        self.TimeComboBox.setItemText(4, _translate("HostEventEdit", "2021"))
        self.TimeComboBox.setItemText(5, _translate("HostEventEdit", "2022"))
        self.TimeComboBox.setItemText(6, _translate("HostEventEdit", "2023"))
        self.TimeComboBox.setItemText(7, _translate("HostEventEdit", "2024"))
        self.TimeComboBox.setItemText(8, _translate("HostEventEdit", "2025"))
        self.TimeComboBox.setItemText(9, _translate("HostEventEdit", "2026"))
        self.TimeComboBox.setItemText(10, _translate("HostEventEdit", "2027"))
        self.TimeComboBox.setItemText(11, _translate("HostEventEdit", "2028"))
        self.TimeComboBox_2.setItemText(0, _translate("HostEventEdit", "Month"))
        self.TimeComboBox_2.setItemText(1, _translate("HostEventEdit", "1"))
        self.TimeComboBox_2.setItemText(2, _translate("HostEventEdit", "2"))
        self.TimeComboBox_2.setItemText(3, _translate("HostEventEdit", "3"))
        self.TimeComboBox_2.setItemText(4, _translate("HostEventEdit", "4"))
        self.TimeComboBox_2.setItemText(5, _translate("HostEventEdit", "5"))
        self.TimeComboBox_2.setItemText(6, _translate("HostEventEdit", "6"))
        self.TimeComboBox_2.setItemText(7, _translate("HostEventEdit", "7"))
        self.TimeComboBox_2.setItemText(8, _translate("HostEventEdit", "8"))
        self.TimeComboBox_2.setItemText(9, _translate("HostEventEdit", "9"))
        self.TimeComboBox_2.setItemText(10, _translate("HostEventEdit", "10"))
        self.TimeComboBox_2.setItemText(11, _translate("HostEventEdit", "11"))
        self.TimeComboBox_2.setItemText(12, _translate("HostEventEdit", "12"))
        self.TimeComboBox_3.setItemText(0, _translate("HostEventEdit", "Day"))
        self.TimeComboBox_3.setItemText(1, _translate("HostEventEdit", "1"))
        self.TimeComboBox_3.setItemText(2, _translate("HostEventEdit", "2"))
        self.TimeComboBox_3.setItemText(3, _translate("HostEventEdit", "3"))
        self.TimeComboBox_3.setItemText(4, _translate("HostEventEdit", "4"))
        self.TimeComboBox_3.setItemText(5, _translate("HostEventEdit", "5"))
        self.TimeComboBox_3.setItemText(6, _translate("HostEventEdit", "6"))
        self.TimeComboBox_3.setItemText(7, _translate("HostEventEdit", "7"))
        self.TimeComboBox_3.setItemText(8, _translate("HostEventEdit", "8"))
        self.TimeComboBox_3.setItemText(9, _translate("HostEventEdit", "9"))
        self.TimeComboBox_3.setItemText(10, _translate("HostEventEdit", "10"))
        self.TimeComboBox_3.setItemText(11, _translate("HostEventEdit", "11"))
        self.TimeComboBox_3.setItemText(12, _translate("HostEventEdit", "12"))
        self.TimeComboBox_3.setItemText(13, _translate("HostEventEdit", "13"))
        self.TimeComboBox_3.setItemText(14, _translate("HostEventEdit", "14"))
        self.TimeComboBox_3.setItemText(15, _translate("HostEventEdit", "15"))
        self.TimeComboBox_3.setItemText(16, _translate("HostEventEdit", "16"))
        self.TimeComboBox_3.setItemText(17, _translate("HostEventEdit", "17"))
        self.TimeComboBox_3.setItemText(18, _translate("HostEventEdit", "18"))
        self.TimeComboBox_3.setItemText(19, _translate("HostEventEdit", "19"))
        self.TimeComboBox_3.setItemText(20, _translate("HostEventEdit", "20"))
        self.TimeComboBox_3.setItemText(21, _translate("HostEventEdit", "21"))
        self.TimeComboBox_3.setItemText(22, _translate("HostEventEdit", "22"))
        self.TimeComboBox_3.setItemText(23, _translate("HostEventEdit", "23"))
        self.TimeComboBox_3.setItemText(24, _translate("HostEventEdit", "24"))
        self.TimeComboBox_3.setItemText(25, _translate("HostEventEdit", "25"))
        self.TimeComboBox_3.setItemText(26, _translate("HostEventEdit", "26"))
        self.TimeComboBox_3.setItemText(27, _translate("HostEventEdit", "27"))
        self.TimeComboBox_3.setItemText(28, _translate("HostEventEdit", "28"))
        self.TimeComboBox_3.setItemText(29, _translate("HostEventEdit", "29"))
        self.TimeComboBox_3.setItemText(30, _translate("HostEventEdit", "30"))
        self.TimeComboBox_3.setItemText(31, _translate("HostEventEdit", "31"))
        self.CatagoryComboBox.setItemText(0, _translate("HostEventEdit", "Tags"))
        self.CatagoryComboBox.setItemText(1, _translate("HostEventEdit", "Sports"))
        self.CatagoryComboBox.setItemText(2, _translate("HostEventEdit", "Social"))
        self.CatagoryComboBox.setItemText(3, _translate("HostEventEdit", "Outdoors"))
        self.CatagoryComboBox.setItemText(4, _translate("HostEventEdit", "Indoors"))
        self.CatagoryComboBox.setItemText(5, _translate("HostEventEdit", "Sightseeing"))
        self.CatagoryComboBox.setItemText(6, _translate("HostEventEdit", "Exhibitions"))
        self.CatagoryComboBox.setItemText(7, _translate("HostEventEdit", "Entertaining"))
        self.CatagoryComboBox.setItemText(8, _translate("HostEventEdit", "Charity"))
        self.CatagoryComboBox.setItemText(9, _translate("HostEventEdit", "Business"))
        self.CatagoryComboBox.setItemText(10, _translate("HostEventEdit", "Anything"))

