# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maindialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainDialog(object):
    def setupUi(self, MainDialog):
        MainDialog.setObjectName("MainDialog")
        MainDialog.resize(745, 453)
        MainDialog.setStyleSheet("")
        self.UserImage = QtWidgets.QGraphicsView(MainDialog)
        self.UserImage.setGeometry(QtCore.QRect(650, 10, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.UserImage.setFont(font)
        self.UserImage.setStyleSheet("border-image: url(./DefaultUser.png);\n"
"")
        self.UserImage.setObjectName("UserImage")
        self.line = QtWidgets.QFrame(MainDialog)
        self.line.setGeometry(QtCore.QRect(610, 0, 2, 453))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line.setFont(font)
        self.line.setStyleSheet("border-image: \\*url();\n"
"background-color: rgb(19, 35, 255);\n"
"")
        self.line.setInputMethodHints(QtCore.Qt.ImhNone)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.NickName = QtWidgets.QLabel(MainDialog)
        self.NickName.setGeometry(QtCore.QRect(645, 76, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.NickName.setFont(font)
        self.NickName.setStyleSheet("border-image: \\*url();")
        self.NickName.setObjectName("NickName")
        self.UpdateProfileButton = QtWidgets.QPushButton(MainDialog)
        self.UpdateProfileButton.setGeometry(QtCore.QRect(640, 100, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.UpdateProfileButton.setFont(font)
        self.UpdateProfileButton.setStyleSheet("")
        self.UpdateProfileButton.setObjectName("UpdateProfileButton")
        self.line_2 = QtWidgets.QFrame(MainDialog)
        self.line_2.setGeometry(QtCore.QRect(610, 151, 140, 2))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line_2.setFont(font)
        self.line_2.setStyleSheet("border-image: \\*url();\n"
"background-color: rgb(19, 35, 255);\n"
"")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_5 = QtWidgets.QLabel(MainDialog)
        self.label_5.setGeometry(QtCore.QRect(623, 154, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border-image: \\*url();")
        self.label_5.setObjectName("label_5")
        self.HostAttendSeeMoreButton = QtWidgets.QPushButton(MainDialog)
        self.HostAttendSeeMoreButton.setGeometry(QtCore.QRect(635, 263, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.HostAttendSeeMoreButton.setFont(font)
        self.HostAttendSeeMoreButton.setStyleSheet("border-image: \\*url();")
        self.HostAttendSeeMoreButton.setObjectName("HostAttendSeeMoreButton")
        self.line_3 = QtWidgets.QFrame(MainDialog)
        self.line_3.setGeometry(QtCore.QRect(610, 301, 140, 2))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line_3.setFont(font)
        self.line_3.setStyleSheet("border-image: \\*url();\n"
"background-color: rgb(19, 35, 255);\n"
"")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.HostEventSeeMoreButton = QtWidgets.QPushButton(MainDialog)
        self.HostEventSeeMoreButton.setGeometry(QtCore.QRect(635, 416, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.HostEventSeeMoreButton.setFont(font)
        self.HostEventSeeMoreButton.setStyleSheet("border-image: \\*url();")
        self.HostEventSeeMoreButton.setObjectName("HostEventSeeMoreButton")
        self.label_12 = QtWidgets.QLabel(MainDialog)
        self.label_12.setGeometry(QtCore.QRect(631, 311, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("border-image: \\*url();")
        self.label_12.setObjectName("label_12")
        self.SearchButton = QtWidgets.QPushButton(MainDialog)
        self.SearchButton.setGeometry(QtCore.QRect(4, 40, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.SearchButton.setFont(font)
        self.SearchButton.setStyleSheet("border-image: \\*url();")
        self.SearchButton.setObjectName("SearchButton")
        self.label_2 = QtWidgets.QLabel(MainDialog)
        self.label_2.setGeometry(QtCore.QRect(10, -3, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        font.setPointSize(34)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-image: \\*url();")
        self.label_2.setObjectName("label_2")
        self.TimeComboBox = QtWidgets.QComboBox(MainDialog)
        self.TimeComboBox.setGeometry(QtCore.QRect(223, 40, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.TimeComboBox.setFont(font)
        self.TimeComboBox.setStyleSheet("border-image: \\*url();")
        self.TimeComboBox.setEditable(False)
        self.TimeComboBox.setObjectName("TimeComboBox")
        self.TimeComboBox.addItem("")
        self.TimeComboBox.addItem("")
        self.TimeComboBox.addItem("")
        self.TimeComboBox.addItem("")
        self.TimeComboBox.addItem("")
        self.TimeComboBox.addItem("")
        self.CatagoryComboBox = QtWidgets.QComboBox(MainDialog)
        self.CatagoryComboBox.setGeometry(QtCore.QRect(90, 40, 131, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.CatagoryComboBox.setFont(font)
        self.CatagoryComboBox.setStyleSheet("border-image: \\*url();")
        self.CatagoryComboBox.setEditable(False)
        self.CatagoryComboBox.setObjectName("CatagoryComboBox")
        self.CatagoryComboBox.addItem("")
        self.CatagoryComboBox.addItem("")
        self.CatagoryComboBox.addItem("")
        self.CatagoryComboBox.addItem("")
        self.CatagoryComboBox.addItem("")
        self.CatagoryComboBox.addItem("")
        self.CatagoryComboBox.addItem("")
        self.CatagoryComboBox.addItem("")
        self.CatagoryComboBox.addItem("")
        self.CatagoryComboBox.addItem("")
        self.CatagoryComboBox.addItem("")
        self.PlaceComboBox = QtWidgets.QComboBox(MainDialog)
        self.PlaceComboBox.setGeometry(QtCore.QRect(367, 40, 101, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.PlaceComboBox.setFont(font)
        self.PlaceComboBox.setStyleSheet("border-image: \\*url();")
        self.PlaceComboBox.setEditable(False)
        self.PlaceComboBox.setObjectName("PlaceComboBox")
        self.PlaceComboBox.addItem("")
        self.KeywordInput = QtWidgets.QLineEdit(MainDialog)
        self.KeywordInput.setGeometry(QtCore.QRect(472, 44, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KeywordInput.setFont(font)
        self.KeywordInput.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.KeywordInput.setStyleSheet("border-image: \\*url();\n"
"border-radius: 5px;\n"
"")
        self.KeywordInput.setText("")
        self.KeywordInput.setClearButtonEnabled(False)
        self.KeywordInput.setObjectName("KeywordInput")
        self.PostEventButton = QtWidgets.QPushButton(MainDialog)
        self.PostEventButton.setGeometry(QtCore.QRect(630, 122, 101, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.PostEventButton.setFont(font)
        self.PostEventButton.setStyleSheet("border-image: \\*url();")
        self.PostEventButton.setObjectName("PostEventButton")
        self.AttendEvent1 = QtWidgets.QPushButton(MainDialog)
        self.AttendEvent1.setGeometry(QtCore.QRect(623, 173, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.AttendEvent1.setFont(font)
        self.AttendEvent1.setStyleSheet("border-image: \\*url();\n"
"background: transparent;\n"
"")
        self.AttendEvent1.setFlat(True)
        self.AttendEvent1.setObjectName("AttendEvent1")
        self.AttendEvent2 = QtWidgets.QPushButton(MainDialog)
        self.AttendEvent2.setGeometry(QtCore.QRect(623, 201, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.AttendEvent2.setFont(font)
        self.AttendEvent2.setStyleSheet("border-image: \\*url();\n"
"background: transparent;\n"
"")
        self.AttendEvent2.setFlat(True)
        self.AttendEvent2.setObjectName("AttendEvent2")
        self.AttendEvent3 = QtWidgets.QPushButton(MainDialog)
        self.AttendEvent3.setGeometry(QtCore.QRect(623, 230, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.AttendEvent3.setFont(font)
        self.AttendEvent3.setStyleSheet("border-image: \\*url();\n"
"background: transparent;\n"
"")
        self.AttendEvent3.setFlat(True)
        self.AttendEvent3.setObjectName("AttendEvent3")
        self.HostEvent1 = QtWidgets.QPushButton(MainDialog)
        self.HostEvent1.setGeometry(QtCore.QRect(623, 330, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.HostEvent1.setFont(font)
        self.HostEvent1.setStyleSheet("border-image: \\*url();\n"
"background: transparent;\n"
"")
        self.HostEvent1.setFlat(True)
        self.HostEvent1.setObjectName("HostEvent1")
        self.HostEvent2 = QtWidgets.QPushButton(MainDialog)
        self.HostEvent2.setGeometry(QtCore.QRect(623, 360, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.HostEvent2.setFont(font)
        self.HostEvent2.setStyleSheet("border-image: \\*url();\n"
"background: transparent;\n"
"")
        self.HostEvent2.setFlat(True)
        self.HostEvent2.setObjectName("HostEvent2")
        self.HostEvent3 = QtWidgets.QPushButton(MainDialog)
        self.HostEvent3.setGeometry(QtCore.QRect(623, 388, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.HostEvent3.setFont(font)
        self.HostEvent3.setStyleSheet("border-image: \\*url();\n"
"background: transparent;\n"
"")
        self.HostEvent3.setFlat(True)
        self.HostEvent3.setObjectName("HostEvent3")
        self.scrollArea = QtWidgets.QScrollArea(MainDialog)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setGeometry(QtCore.QRect(0, 70, 611, 382))
        self.scrollArea.setMinimumSize(QtCore.QSize(611, 370))
        self.scrollArea.setStyleSheet("\n"
"background-color: rgba(43, 230, 255,50)\n"
"\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 609, 1500))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(609, 1500))
        self.scrollAreaWidgetContents.setStyleSheet("border-image: \\*url();\n"
"background-color: rgba(43, 230, 255,50)")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.AttendEvent1_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.AttendEvent1_2.setGeometry(QtCore.QRect(137, 22, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendEvent1_2.setFont(font)
        self.AttendEvent1_2.setStyleSheet("background-color: rgba(43, 230, 255,0);\n"
"background: transparent;\n"
"")
        self.AttendEvent1_2.setFlat(True)
        self.AttendEvent1_2.setObjectName("AttendEvent1_2")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setGeometry(QtCore.QRect(152, 52, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.label_6.setObjectName("label_6")
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setGeometry(QtCore.QRect(280, 49, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.label_14.setObjectName("label_14")
        self.UserImage_2 = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.UserImage_2.setGeometry(QtCore.QRect(20, 20, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.UserImage_2.setFont(font)
        self.UserImage_2.setStyleSheet("background-color: \\*rgba(43, 230, 255,50);\n"
"background-color: rgba(255, 255, 255)")
        self.UserImage_2.setObjectName("UserImage_2")
        self.UserImage_3 = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.UserImage_3.setGeometry(QtCore.QRect(20, 91, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.UserImage_3.setFont(font)
        self.UserImage_3.setStyleSheet("background-color: \\*rgba(43, 230, 255,50);\n"
"background-color: rgba(255, 255, 255)")
        self.UserImage_3.setObjectName("UserImage_3")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setGeometry(QtCore.QRect(152, 123, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.label_7.setObjectName("label_7")
        self.AttendEvent1_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.AttendEvent1_3.setGeometry(QtCore.QRect(137, 93, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendEvent1_3.setFont(font)
        self.AttendEvent1_3.setStyleSheet("background-color: rgba(43, 230, 255,0);\n"
"background: transparent;\n"
"")
        self.AttendEvent1_3.setFlat(True)
        self.AttendEvent1_3.setObjectName("AttendEvent1_3")
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setGeometry(QtCore.QRect(280, 120, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.label_15.setObjectName("label_15")
        self.UserImage_4 = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.UserImage_4.setGeometry(QtCore.QRect(20, 161, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.UserImage_4.setFont(font)
        self.UserImage_4.setStyleSheet("background-color: \\*rgba(43, 230, 255,50);\n"
"background-color: rgba(255, 255, 255)")
        self.UserImage_4.setObjectName("UserImage_4")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setGeometry(QtCore.QRect(152, 193, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.label_8.setObjectName("label_8")
        self.AttendEvent1_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.AttendEvent1_4.setGeometry(QtCore.QRect(137, 163, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendEvent1_4.setFont(font)
        self.AttendEvent1_4.setStyleSheet("background-color: rgba(43, 230, 255,0);\n"
"background: transparent;\n"
"")
        self.AttendEvent1_4.setFlat(True)
        self.AttendEvent1_4.setObjectName("AttendEvent1_4")
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setGeometry(QtCore.QRect(280, 190, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_17.setGeometry(QtCore.QRect(280, 401, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.label_17.setObjectName("label_17")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setGeometry(QtCore.QRect(152, 404, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.label_9.setObjectName("label_9")
        self.UserImage_5 = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.UserImage_5.setGeometry(QtCore.QRect(20, 231, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.UserImage_5.setFont(font)
        self.UserImage_5.setStyleSheet("background-color: \\*rgba(43, 230, 255,50);\n"
"background-color: rgba(255, 255, 255)")
        self.UserImage_5.setObjectName("UserImage_5")
        self.AttendEvent1_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.AttendEvent1_5.setGeometry(QtCore.QRect(137, 304, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendEvent1_5.setFont(font)
        self.AttendEvent1_5.setStyleSheet("background-color: rgba(43, 230, 255,0);\n"
"background: transparent;\n"
"")
        self.AttendEvent1_5.setFlat(True)
        self.AttendEvent1_5.setObjectName("AttendEvent1_5")
        self.UserImage_6 = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.UserImage_6.setGeometry(QtCore.QRect(20, 302, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.UserImage_6.setFont(font)
        self.UserImage_6.setStyleSheet("background-color: \\*rgba(43, 230, 255,50);\n"
"background-color: rgba(255, 255, 255)")
        self.UserImage_6.setObjectName("UserImage_6")
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setGeometry(QtCore.QRect(152, 334, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.label_10.setObjectName("label_10")
        self.AttendEvent1_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.AttendEvent1_6.setGeometry(QtCore.QRect(137, 374, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendEvent1_6.setFont(font)
        self.AttendEvent1_6.setStyleSheet("background-color: rgba(43, 230, 255,0);\n"
"background: transparent;\n"
"")
        self.AttendEvent1_6.setFlat(True)
        self.AttendEvent1_6.setObjectName("AttendEvent1_6")
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setGeometry(QtCore.QRect(152, 263, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.label_11.setObjectName("label_11")
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_18.setGeometry(QtCore.QRect(280, 331, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.label_18.setObjectName("label_18")
        self.AttendEvent1_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.AttendEvent1_7.setGeometry(QtCore.QRect(137, 233, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendEvent1_7.setFont(font)
        self.AttendEvent1_7.setStyleSheet("background-color: rgba(43, 230, 255,0);\n"
"background: transparent;\n"
"")
        self.AttendEvent1_7.setFlat(True)
        self.AttendEvent1_7.setObjectName("AttendEvent1_7")
        self.UserImage_7 = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.UserImage_7.setGeometry(QtCore.QRect(20, 372, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.UserImage_7.setFont(font)
        self.UserImage_7.setStyleSheet("background-color: \\*rgba(43, 230, 255,50);\n"
"background-color: rgba(255, 255, 255)")
        self.UserImage_7.setObjectName("UserImage_7")
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_19.setGeometry(QtCore.QRect(280, 260, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_20.setGeometry(QtCore.QRect(280, 613, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.label_20.setObjectName("label_20")
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setGeometry(QtCore.QRect(152, 616, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.label_13.setObjectName("label_13")
        self.UserImage_8 = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.UserImage_8.setGeometry(QtCore.QRect(20, 443, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.UserImage_8.setFont(font)
        self.UserImage_8.setStyleSheet("background-color: \\*rgba(43, 230, 255,50);\n"
"background-color: rgba(255, 255, 255)")
        self.UserImage_8.setObjectName("UserImage_8")
        self.AttendEvent1_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.AttendEvent1_8.setGeometry(QtCore.QRect(137, 516, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendEvent1_8.setFont(font)
        self.AttendEvent1_8.setStyleSheet("background-color: rgba(43, 230, 255,0);\n"
"background: transparent;\n"
"")
        self.AttendEvent1_8.setFlat(True)
        self.AttendEvent1_8.setObjectName("AttendEvent1_8")
        self.UserImage_9 = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.UserImage_9.setGeometry(QtCore.QRect(20, 514, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.UserImage_9.setFont(font)
        self.UserImage_9.setStyleSheet("background-color: \\*rgba(43, 230, 255,50);\n"
"background-color: rgba(255, 255, 255)")
        self.UserImage_9.setObjectName("UserImage_9")
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_21.setGeometry(QtCore.QRect(152, 546, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.label_21.setObjectName("label_21")
        self.AttendEvent1_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.AttendEvent1_9.setGeometry(QtCore.QRect(137, 586, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendEvent1_9.setFont(font)
        self.AttendEvent1_9.setStyleSheet("background-color: rgba(43, 230, 255,0);\n"
"background: transparent;\n"
"")
        self.AttendEvent1_9.setFlat(True)
        self.AttendEvent1_9.setObjectName("AttendEvent1_9")
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_22.setGeometry(QtCore.QRect(152, 475, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_23.setGeometry(QtCore.QRect(280, 543, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.label_23.setObjectName("label_23")
        self.AttendEvent1_10 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.AttendEvent1_10.setGeometry(QtCore.QRect(137, 445, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendEvent1_10.setFont(font)
        self.AttendEvent1_10.setStyleSheet("background-color: rgba(43, 230, 255,0);\n"
"background: transparent;\n"
"")
        self.AttendEvent1_10.setFlat(True)
        self.AttendEvent1_10.setObjectName("AttendEvent1_10")
        self.UserImage_10 = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.UserImage_10.setGeometry(QtCore.QRect(20, 584, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.UserImage_10.setFont(font)
        self.UserImage_10.setStyleSheet("background-color: \\*rgba(43, 230, 255,50);\n"
"background-color: rgba(255, 255, 255)")
        self.UserImage_10.setObjectName("UserImage_10")
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_24.setGeometry(QtCore.QRect(280, 472, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_25.setGeometry(QtCore.QRect(280, 827, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_26.setGeometry(QtCore.QRect(152, 830, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.label_26.setObjectName("label_26")
        self.UserImage_11 = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.UserImage_11.setGeometry(QtCore.QRect(20, 657, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.UserImage_11.setFont(font)
        self.UserImage_11.setStyleSheet("background-color: \\*rgba(43, 230, 255,50);\n"
"background-color: rgba(255, 255, 255)")
        self.UserImage_11.setObjectName("UserImage_11")
        self.AttendEvent1_11 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.AttendEvent1_11.setGeometry(QtCore.QRect(137, 730, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendEvent1_11.setFont(font)
        self.AttendEvent1_11.setStyleSheet("background-color: rgba(43, 230, 255,0);\n"
"background: transparent;\n"
"")
        self.AttendEvent1_11.setFlat(True)
        self.AttendEvent1_11.setObjectName("AttendEvent1_11")
        self.UserImage_12 = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.UserImage_12.setGeometry(QtCore.QRect(20, 728, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.UserImage_12.setFont(font)
        self.UserImage_12.setStyleSheet("background-color: \\*rgba(43, 230, 255,50);\n"
"background-color: rgba(255, 255, 255)")
        self.UserImage_12.setObjectName("UserImage_12")
        self.label_27 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_27.setGeometry(QtCore.QRect(152, 760, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.label_27.setObjectName("label_27")
        self.AttendEvent1_12 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.AttendEvent1_12.setGeometry(QtCore.QRect(137, 800, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendEvent1_12.setFont(font)
        self.AttendEvent1_12.setStyleSheet("background-color: rgba(43, 230, 255,0);\n"
"background: transparent;\n"
"")
        self.AttendEvent1_12.setFlat(True)
        self.AttendEvent1_12.setObjectName("AttendEvent1_12")
        self.label_28 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_28.setGeometry(QtCore.QRect(152, 689, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_29.setGeometry(QtCore.QRect(280, 757, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.label_29.setObjectName("label_29")
        self.AttendEvent1_13 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.AttendEvent1_13.setGeometry(QtCore.QRect(137, 659, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendEvent1_13.setFont(font)
        self.AttendEvent1_13.setStyleSheet("background-color: rgba(43, 230, 255,0);\n"
"background: transparent;\n"
"")
        self.AttendEvent1_13.setFlat(True)
        self.AttendEvent1_13.setObjectName("AttendEvent1_13")
        self.UserImage_13 = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.UserImage_13.setGeometry(QtCore.QRect(20, 798, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.UserImage_13.setFont(font)
        self.UserImage_13.setStyleSheet("background-color: \\*rgba(43, 230, 255,50);\n"
"background-color: rgba(255, 255, 255)")
        self.UserImage_13.setObjectName("UserImage_13")
        self.label_30 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_30.setGeometry(QtCore.QRect(280, 686, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.label_30.setObjectName("label_30")
        self.UserImage_14 = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.UserImage_14.setGeometry(QtCore.QRect(20, 941, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.UserImage_14.setFont(font)
        self.UserImage_14.setStyleSheet("background-color: \\*rgba(43, 230, 255,50);\n"
"background-color: rgba(255, 255, 255)")
        self.UserImage_14.setObjectName("UserImage_14")
        self.label_31 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_31.setGeometry(QtCore.QRect(280, 970, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.label_31.setObjectName("label_31")
        self.AttendEvent1_14 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.AttendEvent1_14.setGeometry(QtCore.QRect(137, 872, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendEvent1_14.setFont(font)
        self.AttendEvent1_14.setStyleSheet("background-color: rgba(43, 230, 255,0);\n"
"background: transparent;\n"
"")
        self.AttendEvent1_14.setFlat(True)
        self.AttendEvent1_14.setObjectName("AttendEvent1_14")
        self.label_32 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_32.setGeometry(QtCore.QRect(280, 1040, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.label_32.setObjectName("label_32")
        self.AttendEvent1_15 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.AttendEvent1_15.setGeometry(QtCore.QRect(137, 943, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendEvent1_15.setFont(font)
        self.AttendEvent1_15.setStyleSheet("background-color: rgba(43, 230, 255,0);\n"
"background: transparent;\n"
"")
        self.AttendEvent1_15.setFlat(True)
        self.AttendEvent1_15.setObjectName("AttendEvent1_15")
        self.label_33 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_33.setGeometry(QtCore.QRect(152, 1043, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_34.setGeometry(QtCore.QRect(280, 899, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_35.setGeometry(QtCore.QRect(152, 973, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_36.setGeometry(QtCore.QRect(152, 902, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.label_36.setObjectName("label_36")
        self.AttendEvent1_16 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.AttendEvent1_16.setGeometry(QtCore.QRect(137, 1013, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AttendEvent1_16.setFont(font)
        self.AttendEvent1_16.setStyleSheet("background-color: rgba(43, 230, 255,0);\n"
"background: transparent;\n"
"")
        self.AttendEvent1_16.setFlat(True)
        self.AttendEvent1_16.setObjectName("AttendEvent1_16")
        self.UserImage_15 = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.UserImage_15.setGeometry(QtCore.QRect(20, 1011, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.UserImage_15.setFont(font)
        self.UserImage_15.setStyleSheet("background-color: \\*rgba(43, 230, 255,50);\n"
"background-color: rgba(255, 255, 255)")
        self.UserImage_15.setObjectName("UserImage_15")
        self.UserImage_16 = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.UserImage_16.setGeometry(QtCore.QRect(20, 870, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.UserImage_16.setFont(font)
        self.UserImage_16.setStyleSheet("background-color: \\*rgba(43, 230, 255,50);\n"
"background-color: rgba(255, 255, 255)")
        self.UserImage_16.setObjectName("UserImage_16")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.graphicsView = QtWidgets.QGraphicsView(MainDialog)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 751, 461))
        self.graphicsView.setStyleSheet("border-image: url(./bg.png)\n"
"\n"
"")
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView.raise_()
        self.UserImage.raise_()
        self.line.raise_()
        self.NickName.raise_()
        self.UpdateProfileButton.raise_()
        self.line_2.raise_()
        self.label_5.raise_()
        self.HostAttendSeeMoreButton.raise_()
        self.line_3.raise_()
        self.HostEventSeeMoreButton.raise_()
        self.label_12.raise_()
        self.SearchButton.raise_()
        self.label_2.raise_()
        self.TimeComboBox.raise_()
        self.CatagoryComboBox.raise_()
        self.PlaceComboBox.raise_()
        self.KeywordInput.raise_()
        self.PostEventButton.raise_()
        self.AttendEvent1.raise_()
        self.AttendEvent2.raise_()
        self.AttendEvent3.raise_()
        self.HostEvent1.raise_()
        self.HostEvent2.raise_()
        self.HostEvent3.raise_()
        self.scrollArea.raise_()

        self.retranslateUi(MainDialog)
        QtCore.QMetaObject.connectSlotsByName(MainDialog)

    def retranslateUi(self, MainDialog):
        _translate = QtCore.QCoreApplication.translate
        MainDialog.setWindowTitle(_translate("MainDialog", "Dialog"))
        self.NickName.setText(_translate("MainDialog", "Nickname"))
        self.UpdateProfileButton.setText(_translate("MainDialog", "Update"))
        self.label_5.setText(_translate("MainDialog", "Event Attended"))
        self.HostAttendSeeMoreButton.setText(_translate("MainDialog", "See More"))
        self.HostEventSeeMoreButton.setText(_translate("MainDialog", "See More"))
        self.label_12.setText(_translate("MainDialog", "Event Hosted"))
        self.SearchButton.setText(_translate("MainDialog", "Search"))
        self.label_2.setText(_translate("MainDialog", "JoinMe"))
        self.TimeComboBox.setItemText(0, _translate("MainDialog", "Time"))
        self.TimeComboBox.setItemText(1, _translate("MainDialog", "In One Day"))
        self.TimeComboBox.setItemText(2, _translate("MainDialog", "In Three Days"))
        self.TimeComboBox.setItemText(3, _translate("MainDialog", "In One Week"))
        self.TimeComboBox.setItemText(4, _translate("MainDialog", "In One Month"))
        self.TimeComboBox.setItemText(5, _translate("MainDialog", "Any Time"))
        self.CatagoryComboBox.setItemText(0, _translate("MainDialog", "Catagory"))
        self.CatagoryComboBox.setItemText(1, _translate("MainDialog", "Sports"))
        self.CatagoryComboBox.setItemText(2, _translate("MainDialog", "Social"))
        self.CatagoryComboBox.setItemText(3, _translate("MainDialog", "Outdoors"))
        self.CatagoryComboBox.setItemText(4, _translate("MainDialog", "Indoors"))
        self.CatagoryComboBox.setItemText(5, _translate("MainDialog", "Sightseeing"))
        self.CatagoryComboBox.setItemText(6, _translate("MainDialog", "Exhibitions"))
        self.CatagoryComboBox.setItemText(7, _translate("MainDialog", "Entertaining"))
        self.CatagoryComboBox.setItemText(8, _translate("MainDialog", "Charity"))
        self.CatagoryComboBox.setItemText(9, _translate("MainDialog", "Business"))
        self.CatagoryComboBox.setItemText(10, _translate("MainDialog", "Anything"))
        self.PlaceComboBox.setItemText(0, _translate("MainDialog", "Place"))
        self.KeywordInput.setPlaceholderText(_translate("MainDialog", "Keyword."))
        self.PostEventButton.setText(_translate("MainDialog", "Post Event"))
        self.AttendEvent1.setText(_translate("MainDialog", "Event Title1"))
        self.AttendEvent2.setText(_translate("MainDialog", "Event Title2"))
        self.AttendEvent3.setText(_translate("MainDialog", "Event Title3"))
        self.HostEvent1.setText(_translate("MainDialog", "Event Title1"))
        self.HostEvent2.setText(_translate("MainDialog", "Event Title2"))
        self.HostEvent3.setText(_translate("MainDialog", "Event Title3"))
        self.AttendEvent1_2.setText(_translate("MainDialog", "Event Title1"))
        self.label_6.setText(_translate("MainDialog", "Date"))
        self.label_14.setText(_translate("MainDialog", "Address"))
        self.label_7.setText(_translate("MainDialog", "Date"))
        self.AttendEvent1_3.setText(_translate("MainDialog", "Event Title2"))
        self.label_15.setText(_translate("MainDialog", "Address"))
        self.label_8.setText(_translate("MainDialog", "Date"))
        self.AttendEvent1_4.setText(_translate("MainDialog", "Event Title3"))
        self.label_16.setText(_translate("MainDialog", "Address"))
        self.label_17.setText(_translate("MainDialog", "Address"))
        self.label_9.setText(_translate("MainDialog", "Date"))
        self.AttendEvent1_5.setText(_translate("MainDialog", "Event Title5"))
        self.label_10.setText(_translate("MainDialog", "Date"))
        self.AttendEvent1_6.setText(_translate("MainDialog", "Event Title6"))
        self.label_11.setText(_translate("MainDialog", "Date"))
        self.label_18.setText(_translate("MainDialog", "Address"))
        self.AttendEvent1_7.setText(_translate("MainDialog", "Event Title4"))
        self.label_19.setText(_translate("MainDialog", "Address"))
        self.label_20.setText(_translate("MainDialog", "Address"))
        self.label_13.setText(_translate("MainDialog", "Date"))
        self.AttendEvent1_8.setText(_translate("MainDialog", "Event Title8"))
        self.label_21.setText(_translate("MainDialog", "Date"))
        self.AttendEvent1_9.setText(_translate("MainDialog", "Event Title9"))
        self.label_22.setText(_translate("MainDialog", "Date"))
        self.label_23.setText(_translate("MainDialog", "Address"))
        self.AttendEvent1_10.setText(_translate("MainDialog", "Event Title7"))
        self.label_24.setText(_translate("MainDialog", "Address"))
        self.label_25.setText(_translate("MainDialog", "Address"))
        self.label_26.setText(_translate("MainDialog", "Date"))
        self.AttendEvent1_11.setText(_translate("MainDialog", "Event Title11"))
        self.label_27.setText(_translate("MainDialog", "Date"))
        self.AttendEvent1_12.setText(_translate("MainDialog", "Event Title12"))
        self.label_28.setText(_translate("MainDialog", "Date"))
        self.label_29.setText(_translate("MainDialog", "Address"))
        self.AttendEvent1_13.setText(_translate("MainDialog", "Event Title10"))
        self.label_30.setText(_translate("MainDialog", "Address"))
        self.label_31.setText(_translate("MainDialog", "Address"))
        self.AttendEvent1_14.setText(_translate("MainDialog", "Event Title13"))
        self.label_32.setText(_translate("MainDialog", "Address"))
        self.AttendEvent1_15.setText(_translate("MainDialog", "Event Title14"))
        self.label_33.setText(_translate("MainDialog", "Date"))
        self.label_34.setText(_translate("MainDialog", "Address"))
        self.label_35.setText(_translate("MainDialog", "Date"))
        self.label_36.setText(_translate("MainDialog", "Date"))
        self.AttendEvent1_16.setText(_translate("MainDialog", "Event Title15"))

