# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maindialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainDialog(object):
    def setupUi(self, MainDialog):
        MainDialog.setObjectName("MainDialog")
        MainDialog.resize(745, 453)
        MainDialog.setStyleSheet("")
        self.UserImage = QtWidgets.QLabel(MainDialog)
        self.UserImage.setGeometry(QtCore.QRect(650, 10, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.UserImage.setFont(font)
        image_profile = QtGui.QImage('./DefaultUser.png')
        self.UserImage.setPixmap(QtGui.QPixmap.fromImage(image_profile).scaled(self.UserImage.width(),
                                                                               self.UserImage.height()))
        self.UserImage.setObjectName("UserImage")
        self.line = QtWidgets.QFrame(MainDialog)
        self.line.setGeometry(QtCore.QRect(610, 0, 2, 453))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line.setFont(font)
        self.line.setStyleSheet("border-image: \\*url();\n"
"background-color: rgb(19, 35, 255);\n"
"")
        self.line.setInputMethodHints(QtCore.Qt.ImhNone)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.NickName = QtWidgets.QLabel(MainDialog)
        self.NickName.setGeometry(QtCore.QRect(645, 76, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.NickName.setFont(font)
        self.NickName.setStyleSheet("border-image: \\*url();")
        self.NickName.setObjectName("NickName")
        self.UpdateProfileButton = QtWidgets.QPushButton(MainDialog)
        self.UpdateProfileButton.setGeometry(QtCore.QRect(640, 100, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.UpdateProfileButton.setFont(font)
        self.UpdateProfileButton.setStyleSheet("")
        self.UpdateProfileButton.setObjectName("UpdateProfileButton")
        self.line_2 = QtWidgets.QFrame(MainDialog)
        self.line_2.setGeometry(QtCore.QRect(610, 151, 140, 2))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line_2.setFont(font)
        self.line_2.setStyleSheet("border-image: \\*url();\n"
"background-color: rgb(19, 35, 255);\n"
"")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_5 = QtWidgets.QLabel(MainDialog)
        self.label_5.setGeometry(QtCore.QRect(623, 154, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border-image: \\*url();")
        self.label_5.setObjectName("label_5")
        self.HostAttendSeeMoreButton = QtWidgets.QPushButton(MainDialog)
        self.HostAttendSeeMoreButton.setGeometry(QtCore.QRect(635, 263, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.HostAttendSeeMoreButton.setFont(font)
        self.HostAttendSeeMoreButton.setStyleSheet("border-image: \\*url();")
        self.HostAttendSeeMoreButton.setObjectName("HostAttendSeeMoreButton")
        self.line_3 = QtWidgets.QFrame(MainDialog)
        self.line_3.setGeometry(QtCore.QRect(610, 301, 140, 2))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line_3.setFont(font)
        self.line_3.setStyleSheet("border-image: \\*url();\n"
"background-color: rgb(19, 35, 255);\n"
"")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.HostEventSeeMoreButton = QtWidgets.QPushButton(MainDialog)
        self.HostEventSeeMoreButton.setGeometry(QtCore.QRect(635, 416, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.HostEventSeeMoreButton.setFont(font)
        self.HostEventSeeMoreButton.setStyleSheet("border-image: \\*url();")
        self.HostEventSeeMoreButton.setObjectName("HostEventSeeMoreButton")
        self.label_12 = QtWidgets.QLabel(MainDialog)
        self.label_12.setGeometry(QtCore.QRect(631, 311, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("border-image: \\*url();")
        self.label_12.setObjectName("label_12")
        self.SearchButton = QtWidgets.QPushButton(MainDialog)
        self.SearchButton.setGeometry(QtCore.QRect(4, 40, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.SearchButton.setFont(font)
        self.SearchButton.setStyleSheet("border-image: \\*url();")
        self.SearchButton.setObjectName("SearchButton")
        self.label_2 = QtWidgets.QLabel(MainDialog)
        self.label_2.setGeometry(QtCore.QRect(10, -3, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        font.setPointSize(34)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-image: \\*url();")
        self.label_2.setObjectName("label_2")
        self.TimeComboBox = QtWidgets.QComboBox(MainDialog)
        self.TimeComboBox.setGeometry(QtCore.QRect(223, 40, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.TimeComboBox.setFont(font)
        self.TimeComboBox.setStyleSheet("border-image: \\*url();")
        self.TimeComboBox.setEditable(False)
        self.TimeComboBox.setObjectName("TimeComboBox")
        self.TimeComboBox.addItem("")
        self.TimeComboBox.addItem("")
        self.TimeComboBox.addItem("")
        self.TimeComboBox.addItem("")
        self.TimeComboBox.addItem("")
        self.CatagoryComboBox = QtWidgets.QComboBox(MainDialog)
        self.CatagoryComboBox.setGeometry(QtCore.QRect(90, 40, 131, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.CatagoryComboBox.setFont(font)
        self.CatagoryComboBox.setStyleSheet("border-image: \\*url();")
        self.CatagoryComboBox.setEditable(False)
        self.CatagoryComboBox.setObjectName("CatagoryComboBox")
        self.CatagoryComboBox.addItem("")
        self.CatagoryComboBox.addItem("")
        self.CatagoryComboBox.addItem("")
        self.CatagoryComboBox.addItem("")
        self.CatagoryComboBox.addItem("")
        self.CatagoryComboBox.addItem("")
        self.CatagoryComboBox.addItem("")
        self.CatagoryComboBox.addItem("")
        self.CatagoryComboBox.addItem("")
        self.CatagoryComboBox.addItem("")
        self.CatagoryComboBox.addItem("")
        self.PlaceComboBox = QtWidgets.QComboBox(MainDialog)
        self.PlaceComboBox.setGeometry(QtCore.QRect(367, 40, 101, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.PlaceComboBox.setFont(font)
        self.PlaceComboBox.setStyleSheet("border-image: \\*url();")
        self.PlaceComboBox.setEditable(False)
        self.PlaceComboBox.setObjectName("PlaceComboBox")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")
        self.PlaceComboBox.addItem("")

        self.KeywordInput = QtWidgets.QLineEdit(MainDialog)
        self.KeywordInput.setGeometry(QtCore.QRect(472, 44, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KeywordInput.setFont(font)
        self.KeywordInput.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.KeywordInput.setStyleSheet("border-image: \\*url();\n"
"border-radius: 5px;\n"
"")
        self.KeywordInput.setText("")
        self.KeywordInput.setClearButtonEnabled(False)
        self.KeywordInput.setObjectName("KeywordInput")
        self.PostEventButton = QtWidgets.QPushButton(MainDialog)
        self.PostEventButton.setGeometry(QtCore.QRect(630, 122, 101, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.PostEventButton.setFont(font)
        self.PostEventButton.setStyleSheet("border-image: \\*url();")
        self.PostEventButton.setObjectName("PostEventButton")
        self.AttendEvent1 = QtWidgets.QPushButton(MainDialog)
        self.AttendEvent1.setGeometry(QtCore.QRect(623, 173, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.AttendEvent1.setFont(font)
        self.AttendEvent1.setStyleSheet("border-image: \\*url();\n"
"background: transparent;\n"
"")
        self.AttendEvent1.setFlat(True)
        self.AttendEvent1.setObjectName("AttendEvent1")
        self.AttendEvent2 = QtWidgets.QPushButton(MainDialog)
        self.AttendEvent2.setGeometry(QtCore.QRect(623, 201, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.AttendEvent2.setFont(font)
        self.AttendEvent2.setStyleSheet("border-image: \\*url();\n"
"background: transparent;\n"
"")
        self.AttendEvent2.setFlat(True)
        self.AttendEvent2.setObjectName("AttendEvent2")
        self.AttendEvent3 = QtWidgets.QPushButton(MainDialog)
        self.AttendEvent3.setGeometry(QtCore.QRect(623, 230, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.AttendEvent3.setFont(font)
        self.AttendEvent3.setStyleSheet("border-image: \\*url();\n"
"background: transparent;\n"
"")
        self.AttendEvent3.setFlat(True)
        self.AttendEvent3.setObjectName("AttendEvent3")
        self.HostEvent1 = QtWidgets.QPushButton(MainDialog)
        self.HostEvent1.setGeometry(QtCore.QRect(623, 330, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.HostEvent1.setFont(font)
        self.HostEvent1.setStyleSheet("border-image: \\*url();\n"
"background: transparent;\n"
"")
        self.HostEvent1.setFlat(True)
        self.HostEvent1.setObjectName("HostEvent1")
        self.HostEvent2 = QtWidgets.QPushButton(MainDialog)
        self.HostEvent2.setGeometry(QtCore.QRect(623, 360, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.HostEvent2.setFont(font)
        self.HostEvent2.setStyleSheet("border-image: \\*url();\n"
"background: transparent;\n"
"")
        self.HostEvent2.setFlat(True)
        self.HostEvent2.setObjectName("HostEvent2")
        self.HostEvent3 = QtWidgets.QPushButton(MainDialog)
        self.HostEvent3.setGeometry(QtCore.QRect(623, 388, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.HostEvent3.setFont(font)
        self.HostEvent3.setStyleSheet("border-image: \\*url();\n"
"background: transparent;\n"
"")
        self.HostEvent3.setFlat(True)
        self.HostEvent3.setObjectName("HostEvent3")
        self.scrollArea = QtWidgets.QScrollArea(MainDialog)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setGeometry(QtCore.QRect(0, 70, 611, 382))
        self.scrollArea.setMinimumSize(QtCore.QSize(611, 370))
        self.scrollArea.setStyleSheet("\n"
"background-color: rgba(43, 230, 255,50)\n"
"\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 609, 1500))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(609, 1500))
        self.scrollAreaWidgetContents.setStyleSheet("border-image: \\*url();\n"
"background-color: rgba(43, 230, 255,50)")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.ScrollAreaEvent1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.ScrollAreaEvent1.setGeometry(QtCore.QRect(137, 22, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaEvent1.setFont(font)
        self.ScrollAreaEvent1.setStyleSheet("background-color: rgba(43, 230, 255,0);\n"
"\n"
"")
        self.ScrollAreaEvent1.setFlat(True)
        self.ScrollAreaEvent1.setObjectName("ScrollAreaEvent1")
        self.ScrollAreaDate1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.ScrollAreaDate1.setGeometry(QtCore.QRect(152, 52, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaDate1.setFont(font)
        self.ScrollAreaDate1.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.ScrollAreaDate1.setObjectName("ScrollAreaDate1")
        self.ScrollAreaAddress1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaAddress1.setGeometry(QtCore.QRect(280, 49, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaAddress1.setFont(font)
        self.ScrollAreaAddress1.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.ScrollAreaAddress1.setObjectName("ScrollAreaAddress1")
        self.ScrollAreaImage1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaImage1.setGeometry(QtCore.QRect(20, 20, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaImage1.setFont(font)
        self.ScrollAreaImage1.setStyleSheet("background-color: \\*rgba(43, 230, 255,50);\n"
"background-color: rgba(255, 255, 255)")
        self.ScrollAreaImage1.setObjectName("ScrollAreaImage1")
        self.ScrollAreaImage2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaImage2.setGeometry(QtCore.QRect(20, 91, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaImage2.setFont(font)
        self.ScrollAreaImage2.setStyleSheet("background-color: \\*rgba(43, 230, 255,50);\n"
"background-color: rgba(255, 255, 255)")
        self.ScrollAreaImage2.setObjectName("ScrollAreaImage2")
        self.ScrollAreaDate2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaDate2.setGeometry(QtCore.QRect(152, 123, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaDate2.setFont(font)
        self.ScrollAreaDate2.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.ScrollAreaDate2.setObjectName("ScrollAreaDate2")
        self.ScrollAreaEvent2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.ScrollAreaEvent2.setGeometry(QtCore.QRect(137, 93, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaEvent2.setFont(font)
        self.ScrollAreaEvent2.setStyleSheet("background-color: rgba(43, 230, 255,0);\n"
"background: transparent;\n"
"")
        self.ScrollAreaEvent2.setFlat(True)
        self.ScrollAreaEvent2.setObjectName("ScrollAreaEvent2")
        self.ScrollAreaAddress2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaAddress2.setGeometry(QtCore.QRect(280, 120, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaAddress2.setFont(font)
        self.ScrollAreaAddress2.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.ScrollAreaAddress2.setObjectName("ScrollAreaAddress2")
        self.ScrollAreaImage3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaImage3.setGeometry(QtCore.QRect(20, 161, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaImage3.setFont(font)
        self.ScrollAreaImage3.setStyleSheet("background-color: \\*rgba(43, 230, 255,50);\n"
"background-color: rgba(255, 255, 255)")
        self.ScrollAreaImage3.setObjectName("ScrollAreaImage3")
        self.ScrollAreaDate3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaDate3.setGeometry(QtCore.QRect(152, 193, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaDate3.setFont(font)
        self.ScrollAreaDate3.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.ScrollAreaDate3.setObjectName("ScrollAreaDate3")
        self.ScrollAreaEvent3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.ScrollAreaEvent3.setGeometry(QtCore.QRect(137, 163, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaEvent3.setFont(font)
        self.ScrollAreaEvent3.setStyleSheet("background-color: rgba(43, 230, 255,0);\n"
"background: transparent;\n"
"")
        self.ScrollAreaEvent3.setFlat(True)
        self.ScrollAreaEvent3.setObjectName("ScrollAreaEvent3")
        self.ScrollAreaAddress3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaAddress3.setGeometry(QtCore.QRect(280, 190, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaAddress3.setFont(font)
        self.ScrollAreaAddress3.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.ScrollAreaAddress3.setObjectName("ScrollAreaAddress3")
        self.ScrollAreaAddress6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaAddress6.setGeometry(QtCore.QRect(280, 401, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaAddress6.setFont(font)
        self.ScrollAreaAddress6.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.ScrollAreaAddress6.setObjectName("ScrollAreaAddress6")
        self.ScrollAreaDate6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaDate6.setGeometry(QtCore.QRect(152, 404, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaDate6.setFont(font)
        self.ScrollAreaDate6.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.ScrollAreaDate6.setObjectName("ScrollAreaDate6")
        self.ScrollAreaImage4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaImage4.setGeometry(QtCore.QRect(20, 231, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaImage4.setFont(font)
        self.ScrollAreaImage4.setStyleSheet("background-color: \\*rgba(43, 230, 255,50);\n"
"background-color: rgba(255, 255, 255)")
        self.ScrollAreaImage4.setObjectName("ScrollAreaImage4")
        self.ScrollAreaEvent5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.ScrollAreaEvent5.setGeometry(QtCore.QRect(137, 304, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaEvent5.setFont(font)
        self.ScrollAreaEvent5.setStyleSheet("background-color: rgba(43, 230, 255,0);\n"
"background: transparent;\n"
"")
        self.ScrollAreaEvent5.setFlat(True)
        self.ScrollAreaEvent5.setObjectName("ScrollAreaEvent5")
        self.ScrollAreaImage5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaImage5.setGeometry(QtCore.QRect(20, 302, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaImage5.setFont(font)
        self.ScrollAreaImage5.setStyleSheet("background-color: \\*rgba(43, 230, 255,50);\n"
"background-color: rgba(255, 255, 255)")
        self.ScrollAreaImage5.setObjectName("ScrollAreaImage5")
        self.ScrollAreaDate5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaDate5.setGeometry(QtCore.QRect(152, 334, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaDate5.setFont(font)
        self.ScrollAreaDate5.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.ScrollAreaDate5.setObjectName("ScrollAreaDate5")
        self.ScrollAreaEvent6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.ScrollAreaEvent6.setGeometry(QtCore.QRect(137, 374, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaEvent6.setFont(font)
        self.ScrollAreaEvent6.setStyleSheet("background-color: rgba(43, 230, 255,0);\n"
"background: transparent;\n"
"")
        self.ScrollAreaEvent6.setFlat(True)
        self.ScrollAreaEvent6.setObjectName("ScrollAreaEvent6")
        self.ScrollAreaDate4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaDate4.setGeometry(QtCore.QRect(152, 263, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaDate4.setFont(font)
        self.ScrollAreaDate4.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.ScrollAreaDate4.setObjectName("ScrollAreaDate4")
        self.ScrollAreaAddress5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaAddress5.setGeometry(QtCore.QRect(280, 331, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaAddress5.setFont(font)
        self.ScrollAreaAddress5.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.ScrollAreaAddress5.setObjectName("ScrollAreaAddress5")
        self.ScrollAreaEvent4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.ScrollAreaEvent4.setGeometry(QtCore.QRect(137, 233, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaEvent4.setFont(font)
        self.ScrollAreaEvent4.setStyleSheet("background-color: rgba(43, 230, 255,0);\n"
"background: transparent;\n"
"")
        self.ScrollAreaEvent4.setFlat(True)
        self.ScrollAreaEvent4.setObjectName("ScrollAreaEvent4")
        self.ScrollAreaImage6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaImage6.setGeometry(QtCore.QRect(20, 372, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaImage6.setFont(font)
        self.ScrollAreaImage6.setStyleSheet("background-color: \\*rgba(43, 230, 255,50);\n"
"background-color: rgba(255, 255, 255)")
        self.ScrollAreaImage6.setObjectName("ScrollAreaImage6")
        self.ScrollAreaAddress4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaAddress4.setGeometry(QtCore.QRect(280, 260, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaAddress4.setFont(font)
        self.ScrollAreaAddress4.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.ScrollAreaAddress4.setObjectName("ScrollAreaAddress4")
        self.ScrollAreaAddress9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaAddress9.setGeometry(QtCore.QRect(280, 613, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaAddress9.setFont(font)
        self.ScrollAreaAddress9.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.ScrollAreaAddress9.setObjectName("ScrollAreaAddress9")
        self.ScrollAreaDate9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaDate9.setGeometry(QtCore.QRect(152, 616, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaDate9.setFont(font)
        self.ScrollAreaDate9.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.ScrollAreaDate9.setObjectName("ScrollAreaDate9")
        self.ScrollAreaImage7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaImage7.setGeometry(QtCore.QRect(20, 443, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaImage7.setFont(font)
        self.ScrollAreaImage7.setStyleSheet("background-color: \\*rgba(43, 230, 255,50);\n"
"background-color: rgba(255, 255, 255)")
        self.ScrollAreaImage7.setObjectName("ScrollAreaImage7")
        self.ScrollAreaEvent8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.ScrollAreaEvent8.setGeometry(QtCore.QRect(137, 516, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaEvent8.setFont(font)
        self.ScrollAreaEvent8.setStyleSheet("background-color: rgba(43, 230, 255,0);\n"
"background: transparent;\n"
"")
        self.ScrollAreaEvent8.setFlat(True)
        self.ScrollAreaEvent8.setObjectName("ScrollAreaEvent8")
        self.ScrollAreaImage8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaImage8.setGeometry(QtCore.QRect(20, 514, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaImage8.setFont(font)
        self.ScrollAreaImage8.setStyleSheet("background-color: \\*rgba(43, 230, 255,50);\n"
"background-color: rgba(255, 255, 255)")
        self.ScrollAreaImage8.setObjectName("ScrollAreaImage8")
        self.ScrollAreaDate8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaDate8.setGeometry(QtCore.QRect(152, 546, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaDate8.setFont(font)
        self.ScrollAreaDate8.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.ScrollAreaDate8.setObjectName("ScrollAreaDate8")
        self.ScrollAreaEvent9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.ScrollAreaEvent9.setGeometry(QtCore.QRect(137, 586, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaEvent9.setFont(font)
        self.ScrollAreaEvent9.setStyleSheet("background-color: rgba(43, 230, 255,0);\n"
"background: transparent;\n"
"")
        self.ScrollAreaEvent9.setFlat(True)
        self.ScrollAreaEvent9.setObjectName("ScrollAreaEvent9")
        self.ScrollAreaDate7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaDate7.setGeometry(QtCore.QRect(152, 475, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaDate7.setFont(font)
        self.ScrollAreaDate7.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.ScrollAreaDate7.setObjectName("ScrollAreaDate7")
        self.ScrollAreaAddress8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaAddress8.setGeometry(QtCore.QRect(280, 543, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaAddress8.setFont(font)
        self.ScrollAreaAddress8.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.ScrollAreaAddress8.setObjectName("ScrollAreaAddress8")
        self.ScrollAreaEvent7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.ScrollAreaEvent7.setGeometry(QtCore.QRect(137, 445, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaEvent7.setFont(font)
        self.ScrollAreaEvent7.setStyleSheet("background-color: rgba(43, 230, 255,0);\n"
"background: transparent;\n"
"")
        self.ScrollAreaEvent7.setFlat(True)
        self.ScrollAreaEvent7.setObjectName("ScrollAreaEvent7")
        self.ScrollAreaImage9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaImage9.setGeometry(QtCore.QRect(20, 584, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaImage9.setFont(font)
        self.ScrollAreaImage9.setStyleSheet("background-color: \\*rgba(43, 230, 255,50);\n"
"background-color: rgba(255, 255, 255)")
        self.ScrollAreaImage9.setObjectName("ScrollAreaImage9")
        self.ScrollAreaAddress7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaAddress7.setGeometry(QtCore.QRect(280, 472, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaAddress7.setFont(font)
        self.ScrollAreaAddress7.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.ScrollAreaAddress7.setObjectName("ScrollAreaAddress7")
        self.ScrollAreaAddress12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaAddress12.setGeometry(QtCore.QRect(280, 827, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaAddress12.setFont(font)
        self.ScrollAreaAddress12.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.ScrollAreaAddress12.setObjectName("ScrollAreaAddress12")
        self.ScrollAreaDate12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaDate12.setGeometry(QtCore.QRect(152, 830, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaDate12.setFont(font)
        self.ScrollAreaDate12.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.ScrollAreaDate12.setObjectName("ScrollAreaDate12")
        self.ScrollAreaImage10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaImage10.setGeometry(QtCore.QRect(20, 657, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaImage10.setFont(font)
        self.ScrollAreaImage10.setStyleSheet("background-color: \\*rgba(43, 230, 255,50);\n"
"background-color: rgba(255, 255, 255)")
        self.ScrollAreaImage10.setObjectName("ScrollAreaImage10")
        self.ScrollAreaEvent11 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.ScrollAreaEvent11.setGeometry(QtCore.QRect(137, 730, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaEvent11.setFont(font)
        self.ScrollAreaEvent11.setStyleSheet("background-color: rgba(43, 230, 255,0);\n"
"background: transparent;\n"
"")
        self.ScrollAreaEvent11.setFlat(True)
        self.ScrollAreaEvent11.setObjectName("ScrollAreaEvent11")
        self.ScrollAreaImage11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaImage11.setGeometry(QtCore.QRect(20, 728, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaImage11.setFont(font)
        self.ScrollAreaImage11.setStyleSheet("background-color: \\*rgba(43, 230, 255,50);\n"
"background-color: rgba(255, 255, 255)")
        self.ScrollAreaImage11.setObjectName("ScrollAreaImage11")
        self.ScrollAreaDate11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaDate11.setGeometry(QtCore.QRect(152, 760, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaDate11.setFont(font)
        self.ScrollAreaDate11.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.ScrollAreaDate11.setObjectName("ScrollAreaDate11")
        self.ScrollAreaEvent12 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.ScrollAreaEvent12.setGeometry(QtCore.QRect(137, 800, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaEvent12.setFont(font)
        self.ScrollAreaEvent12.setStyleSheet("background-color: rgba(43, 230, 255,0);\n"
"background: transparent;\n"
"")
        self.ScrollAreaEvent12.setFlat(True)
        self.ScrollAreaEvent12.setObjectName("ScrollAreaEvent12")
        self.ScrollAreaDate10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaDate10.setGeometry(QtCore.QRect(152, 689, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaDate10.setFont(font)
        self.ScrollAreaDate10.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.ScrollAreaDate10.setObjectName("ScrollAreaDate10")
        self.ScrollAreaAddress11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaAddress11.setGeometry(QtCore.QRect(280, 757, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaAddress11.setFont(font)
        self.ScrollAreaAddress11.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.ScrollAreaAddress11.setObjectName("ScrollAreaAddress11")
        self.ScrollAreaEvent10 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.ScrollAreaEvent10.setGeometry(QtCore.QRect(137, 659, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaEvent10.setFont(font)
        self.ScrollAreaEvent10.setStyleSheet("background-color: rgba(43, 230, 255,0);\n"
"background: transparent;\n"
"")
        self.ScrollAreaEvent10.setFlat(True)
        self.ScrollAreaEvent10.setObjectName("ScrollAreaEvent10")
        self.ScrollAreaImage12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaImage12.setGeometry(QtCore.QRect(20, 798, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaImage12.setFont(font)
        self.ScrollAreaImage12.setStyleSheet("background-color: \\*rgba(43, 230, 255,50);\n"
"background-color: rgba(255, 255, 255)")
        self.ScrollAreaImage12.setObjectName("ScrollAreaImage12")
        self.ScrollAreaAddress10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaAddress10.setGeometry(QtCore.QRect(280, 686, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaAddress10.setFont(font)
        self.ScrollAreaAddress10.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.ScrollAreaAddress10.setObjectName("ScrollAreaAddress10")
        self.ScrollAreaImage14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaImage14.setGeometry(QtCore.QRect(20, 941, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaImage14.setFont(font)
        self.ScrollAreaImage14.setStyleSheet("background-color: \\*rgba(43, 230, 255,50);\n"
"background-color: rgba(255, 255, 255)")
        self.ScrollAreaImage14.setObjectName("ScrollAreaImage14")
        self.ScrollAreaAddress14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaAddress14.setGeometry(QtCore.QRect(280, 970, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaAddress14.setFont(font)
        self.ScrollAreaAddress14.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.ScrollAreaAddress14.setObjectName("ScrollAreaAddress14")
        self.ScrollAreaEvent13 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.ScrollAreaEvent13.setGeometry(QtCore.QRect(137, 872, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaEvent13.setFont(font)
        self.ScrollAreaEvent13.setStyleSheet("background-color: rgba(43, 230, 255,0);\n"
"background: transparent;\n"
"")
        self.ScrollAreaEvent13.setFlat(True)
        self.ScrollAreaEvent13.setObjectName("ScrollAreaEvent13")
        self.ScrollAreaAddress15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaAddress15.setGeometry(QtCore.QRect(280, 1040, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaAddress15.setFont(font)
        self.ScrollAreaAddress15.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.ScrollAreaAddress15.setObjectName("ScrollAreaAddress15")
        self.ScrollAreaEvent14 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.ScrollAreaEvent14.setGeometry(QtCore.QRect(137, 943, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaEvent14.setFont(font)
        self.ScrollAreaEvent14.setStyleSheet("background-color: rgba(43, 230, 255,0);\n"
"background: transparent;\n"
"")
        self.ScrollAreaEvent14.setFlat(True)
        self.ScrollAreaEvent14.setObjectName("ScrollAreaEvent14")
        self.ScrollAreaDate15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaDate15.setGeometry(QtCore.QRect(152, 1043, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaDate15.setFont(font)
        self.ScrollAreaDate15.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.ScrollAreaDate15.setObjectName("ScrollAreaDate15")
        self.ScrollAreaAddress13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaAddress13.setGeometry(QtCore.QRect(280, 899, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaAddress13.setFont(font)
        self.ScrollAreaAddress13.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.ScrollAreaAddress13.setObjectName("ScrollAreaAddress13")
        self.ScrollAreaDate14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaDate14.setGeometry(QtCore.QRect(152, 973, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaDate14.setFont(font)
        self.ScrollAreaDate14.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.ScrollAreaDate14.setObjectName("ScrollAreaDate14")
        self.ScrollAreaDate13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaDate13.setGeometry(QtCore.QRect(152, 902, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaDate13.setFont(font)
        self.ScrollAreaDate13.setStyleSheet("background-color: rgba(43, 230, 255,0)")
        self.ScrollAreaDate13.setObjectName("ScrollAreaDate13")
        self.ScrollAreaEvent15 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.ScrollAreaEvent15.setGeometry(QtCore.QRect(137, 1013, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaEvent15.setFont(font)
        self.ScrollAreaEvent15.setStyleSheet("background-color: rgba(43, 230, 255,0);\n"
"background: transparent;\n"
"")
        self.ScrollAreaEvent15.setFlat(True)
        self.ScrollAreaEvent15.setObjectName("ScrollAreaEvent15")
        self.ScrollAreaImage15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaImage15.setGeometry(QtCore.QRect(20, 1011, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaImage15.setFont(font)
        self.ScrollAreaImage15.setStyleSheet("background-color: \\*rgba(43, 230, 255,50);\n"
"background-color: rgba(255, 255, 255)")
        self.ScrollAreaImage15.setObjectName("ScrollAreaImage15")
        self.ScrollAreaImage13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ScrollAreaImage13.setGeometry(QtCore.QRect(20, 870, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScrollAreaImage13.setFont(font)
        self.ScrollAreaImage13.setStyleSheet("background-color: \\*rgba(43, 230, 255,50);\n"
"background-color: rgba(255, 255, 255)")
        self.ScrollAreaImage13.setObjectName("ScrollAreaImage13")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.graphicsView = QtWidgets.QLabel(MainDialog)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 751, 461))
        self.graphicsView.setStyleSheet("border-image: url(./bg.png)\n"
"\n"
"")
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView.raise_()
        self.UserImage.raise_()
        self.line.raise_()
        self.NickName.raise_()
        self.UpdateProfileButton.raise_()
        self.line_2.raise_()
        self.label_5.raise_()
        self.HostAttendSeeMoreButton.raise_()
        self.line_3.raise_()
        self.HostEventSeeMoreButton.raise_()
        self.label_12.raise_()
        self.SearchButton.raise_()
        self.label_2.raise_()
        self.TimeComboBox.raise_()
        self.CatagoryComboBox.raise_()
        self.PlaceComboBox.raise_()
        self.KeywordInput.raise_()
        self.PostEventButton.raise_()
        self.AttendEvent1.raise_()
        self.AttendEvent2.raise_()
        self.AttendEvent3.raise_()
        self.HostEvent1.raise_()
        self.HostEvent2.raise_()
        self.HostEvent3.raise_()
        self.scrollArea.raise_()
        self.AttendEventList = [self.AttendEvent1, self.AttendEvent2, self.AttendEvent3]
        self.HostEventList = [self.HostEvent1, self.HostEvent2, self.HostEvent3]
        self.ScrollAreaList = [{'title':self.ScrollAreaEvent1,
                                'date':self.ScrollAreaDate1,
                                'address':self.ScrollAreaAddress1,
                                'image':self.ScrollAreaImage1},
                               {'title': self.ScrollAreaEvent2,
                                'date': self.ScrollAreaDate2,
                                'address': self.ScrollAreaAddress2,
                                'image': self.ScrollAreaImage2},
                               {'title': self.ScrollAreaEvent3,
                                'date': self.ScrollAreaDate3,
                                'address': self.ScrollAreaAddress3,
                                'image': self.ScrollAreaImage3},
                               {'title': self.ScrollAreaEvent4,
                                'date': self.ScrollAreaDate4,
                                'address': self.ScrollAreaAddress4,
                                'image': self.ScrollAreaImage4},
                               {'title': self.ScrollAreaEvent5,
                                'date': self.ScrollAreaDate5,
                                'address': self.ScrollAreaAddress5,
                                'image': self.ScrollAreaImage5},
                               {'title': self.ScrollAreaEvent6,
                                'date': self.ScrollAreaDate6,
                                'address': self.ScrollAreaAddress6,
                                'image': self.ScrollAreaImage6},
                               {'title': self.ScrollAreaEvent7,
                                'date': self.ScrollAreaDate7,
                                'address': self.ScrollAreaAddress7,
                                'image': self.ScrollAreaImage7},
                               {'title': self.ScrollAreaEvent8,
                                'date': self.ScrollAreaDate8,
                                'address': self.ScrollAreaAddress8,
                                'image': self.ScrollAreaImage8},
                               {'title': self.ScrollAreaEvent9,
                                'date': self.ScrollAreaDate9,
                                'address': self.ScrollAreaAddress9,
                                'image': self.ScrollAreaImage9},
                               {'title': self.ScrollAreaEvent10,
                                'date': self.ScrollAreaDate10,
                                'address': self.ScrollAreaAddress10,
                                'image': self.ScrollAreaImage10},
                               {'title': self.ScrollAreaEvent11,
                                'date': self.ScrollAreaDate11,
                                'address': self.ScrollAreaAddress11,
                                'image': self.ScrollAreaImage11},
                               {'title': self.ScrollAreaEvent12,
                                'date': self.ScrollAreaDate12,
                                'address': self.ScrollAreaAddress12,
                                'image': self.ScrollAreaImage12},
                               {'title': self.ScrollAreaEvent13,
                                'date': self.ScrollAreaDate13,
                                'address': self.ScrollAreaAddress13,
                                'image': self.ScrollAreaImage13},
                               {'title': self.ScrollAreaEvent14,
                                'date': self.ScrollAreaDate14,
                                'address': self.ScrollAreaAddress14,
                                'image': self.ScrollAreaImage14},
                               {'title': self.ScrollAreaEvent15,
                                'date': self.ScrollAreaDate15,
                                'address': self.ScrollAreaAddress15,
                                'image': self.ScrollAreaImage15},
                               ]
        self.retranslateUi(MainDialog)
        QtCore.QMetaObject.connectSlotsByName(MainDialog)

    def retranslateUi(self, MainDialog):
        _translate = QtCore.QCoreApplication.translate
        MainDialog.setWindowTitle(_translate("MainDialog", "Dialog"))
        self.NickName.setText(_translate("MainDialog", "Nickname"))
        self.UpdateProfileButton.setText(_translate("MainDialog", "Update"))
        self.label_5.setText(_translate("MainDialog", "Event Attended"))
        self.HostAttendSeeMoreButton.setText(_translate("MainDialog", "Refresh"))
        self.HostEventSeeMoreButton.setText(_translate("MainDialog", "Refresh"))
        self.label_12.setText(_translate("MainDialog", "Event Hosted"))
        self.SearchButton.setText(_translate("MainDialog", "Search"))
        self.label_2.setText(_translate("MainDialog", "JoinMe"))
        self.TimeComboBox.setItemText(0, _translate("MainDialog", "Time"))
        self.TimeComboBox.setItemText(1, _translate("MainDialog", "In One Day"))
        self.TimeComboBox.setItemText(2, _translate("MainDialog", "In Three Days"))
        self.TimeComboBox.setItemText(3, _translate("MainDialog", "In One Week"))
        self.TimeComboBox.setItemText(4, _translate("MainDialog", "In One Month"))
        self.CatagoryComboBox.setItemText(0, _translate("MainDialog", "Category"))
        self.CatagoryComboBox.setItemText(1, _translate("MainDialog", "sports"))
        self.CatagoryComboBox.setItemText(2, _translate("MainDialog", "social"))
        self.CatagoryComboBox.setItemText(3, _translate("MainDialog", "outdoors"))
        self.CatagoryComboBox.setItemText(4, _translate("MainDialog", "indoors"))
        self.CatagoryComboBox.setItemText(5, _translate("MainDialog", "sightseeing"))
        self.CatagoryComboBox.setItemText(6, _translate("MainDialog", "exhibitions"))
        self.CatagoryComboBox.setItemText(7, _translate("MainDialog", "entertaining"))
        self.CatagoryComboBox.setItemText(8, _translate("MainDialog", "charity"))
        self.CatagoryComboBox.setItemText(9, _translate("MainDialog", "business"))
        self.CatagoryComboBox.setItemText(10, _translate("MainDialog", "anything"))
        self.PlaceComboBox.setItemText(0, _translate("MainDialog", "Your Place"))

        us_states = ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
                     'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia',
                     'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa',
                     'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
                     'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri',
                     'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey',
                     'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio',
                     'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina',
                     'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont',
                     'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming']

        for i, state in enumerate(us_states):
            self.PlaceComboBox.setItemText(i+1, _translate("MainDialog", state))

        self.KeywordInput.setPlaceholderText(_translate("MainDialog", "Keyword"))
        self.PostEventButton.setText(_translate("MainDialog", "Post Event"))
        
        AttendEventLength = len(self.AttendEventList)
        for i in range(AttendEventLength):
            self.AttendEventList[i].setText(_translate("MainDialog", "Event Title"+str(i+1)))

        HostEventLength = len(self.HostEventList)
        for i in range(HostEventLength):
            self.HostEventList[i].setText(_translate("MainDialog", "Event Title" + str(i + 1)))
        
        ScrollEventLength = len(self.ScrollAreaList)
        for i in range(ScrollEventLength):
            currentEvent = self.ScrollAreaList[i]
            currentEvent['title'].setText(_translate("MainDialog", "Event Title"+str(i+1)))
            currentEvent['date'].setText(_translate("MainDialog", "Date"))
            currentEvent['address'].setText(_translate("MainDialog", "Address"))
            
        
        '''
        self.AttendEvent1.setText(_translate("MainDialog", "Event Title1"))
        self.AttendEvent2.setText(_translate("MainDialog", "Event Title2"))
        self.AttendEvent3.setText(_translate("MainDialog", "Event Title3"))
        self.HostEvent1.setText(_translate("MainDialog", "Event Title1"))
        self.HostEvent2.setText(_translate("MainDialog", "Event Title2"))
        self.HostEvent3.setText(_translate("MainDialog", "Event Title3"))
        '''
        
        '''
        self.ScrollAreaEvent1.setText(_translate("MainDialog", "Event Title1"))
        self.ScrollAreaDate1.setText(_translate("MainDialog", "Date"))
        self.ScrollAreaAddress1.setText(_translate("MainDialog", "Address"))
        self.ScrollAreaDate2.setText(_translate("MainDialog", "Date"))
        self.ScrollAreaEvent2.setText(_translate("MainDialog", "Event Title2"))
        self.ScrollAreaAddress2.setText(_translate("MainDialog", "Address"))
        self.ScrollAreaDate3.setText(_translate("MainDialog", "Date"))
        self.ScrollAreaEvent3.setText(_translate("MainDialog", "Event Title3"))
        self.ScrollAreaAddress3.setText(_translate("MainDialog", "Address"))
        self.ScrollAreaAddress6.setText(_translate("MainDialog", "Address"))
        self.ScrollAreaDate6.setText(_translate("MainDialog", "Date"))
        self.ScrollAreaEvent5.setText(_translate("MainDialog", "Event Title5"))
        self.ScrollAreaDate5.setText(_translate("MainDialog", "Date"))
        self.ScrollAreaEvent6.setText(_translate("MainDialog", "Event Title6"))
        self.ScrollAreaDate4.setText(_translate("MainDialog", "Date"))
        self.ScrollAreaAddress5.setText(_translate("MainDialog", "Address"))
        self.ScrollAreaEvent4.setText(_translate("MainDialog", "Event Title4"))
        self.ScrollAreaAddress4.setText(_translate("MainDialog", "Address"))
        self.ScrollAreaAddress9.setText(_translate("MainDialog", "Address"))
        self.ScrollAreaDate9.setText(_translate("MainDialog", "Date"))
        self.ScrollAreaEvent8.setText(_translate("MainDialog", "Event Title8"))
        self.ScrollAreaDate8.setText(_translate("MainDialog", "Date"))
        self.ScrollAreaEvent9.setText(_translate("MainDialog", "Event Title9"))
        self.ScrollAreaDate7.setText(_translate("MainDialog", "Date"))
        self.ScrollAreaAddress8.setText(_translate("MainDialog", "Address"))
        self.ScrollAreaEvent7.setText(_translate("MainDialog", "Event Title7"))
        self.ScrollAreaAddress7.setText(_translate("MainDialog", "Address"))
        self.ScrollAreaAddress12.setText(_translate("MainDialog", "Address"))
        self.ScrollAreaDate12.setText(_translate("MainDialog", "Date"))
        self.ScrollAreaEvent11.setText(_translate("MainDialog", "Event Title11"))
        self.ScrollAreaDate11.setText(_translate("MainDialog", "Date"))
        self.ScrollAreaEvent12.setText(_translate("MainDialog", "Event Title12"))
        self.ScrollAreaDate10.setText(_translate("MainDialog", "Date"))
        self.ScrollAreaAddress11.setText(_translate("MainDialog", "Address"))
        self.ScrollAreaEvent10.setText(_translate("MainDialog", "Event Title10"))
        self.ScrollAreaAddress10.setText(_translate("MainDialog", "Address"))
        self.ScrollAreaAddress14.setText(_translate("MainDialog", "Address"))
        self.ScrollAreaEvent13.setText(_translate("MainDialog", "Event Title13"))
        self.ScrollAreaAddress15.setText(_translate("MainDialog", "Address"))
        self.ScrollAreaEvent14.setText(_translate("MainDialog", "Event Title14"))
        self.ScrollAreaDate15.setText(_translate("MainDialog", "Date"))
        self.ScrollAreaAddress13.setText(_translate("MainDialog", "Address"))
        self.ScrollAreaDate14.setText(_translate("MainDialog", "Date"))
        self.ScrollAreaDate13.setText(_translate("MainDialog", "Date"))
        self.ScrollAreaEvent15.setText(_translate("MainDialog", "Event Title15"))

        '''
        
