# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userprofiledisplay.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserProfileDisplay(object):
    def setupUi(self, UserProfileDisplay):
        UserProfileDisplay.setObjectName("UserProfileDisplay")
        UserProfileDisplay.resize(745, 453)
        UserProfileDisplay.setStyleSheet("")
        self.label_2 = QtWidgets.QLabel(UserProfileDisplay)
        self.label_2.setGeometry(QtCore.QRect(70, 170, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        font.setPointSize(40)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-image: \\*url();")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(UserProfileDisplay)
        self.label_4.setGeometry(QtCore.QRect(220, 160, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border-image: \\*url();")
        self.label_4.setObjectName("label_4")
        self.GenderOutput = QtWidgets.QLabel(UserProfileDisplay)
        self.GenderOutput.setGeometry(QtCore.QRect(438, 131, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.GenderOutput.setFont(font)
        self.GenderOutput.setStyleSheet("border-image: \\*url();")
        self.GenderOutput.setObjectName("GenderOutput")
        self.FirstNameOutput = QtWidgets.QLabel(UserProfileDisplay)
        self.FirstNameOutput.setGeometry(QtCore.QRect(220, 132, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.FirstNameOutput.setFont(font)
        self.FirstNameOutput.setStyleSheet("border-image: \\*url();")
        self.FirstNameOutput.setObjectName("FirstNameOutput")
        self.UserImageOutput = QtWidgets.QLabel(UserProfileDisplay)
        self.UserImageOutput.setGeometry(QtCore.QRect(220, 72, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.UserImageOutput.setFont(font)
        self.UserImageOutput.setStyleSheet("border-image: url(./Transparency.png);\n""\n""")
        self.UserImageOutput.setObjectName("UserImageOutput")
        self.label_8 = QtWidgets.QLabel(UserProfileDisplay)
        self.label_8.setGeometry(QtCore.QRect(220, 190, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border-image: \\*url();")
        self.label_8.setObjectName("label_8")
        self.NicknameOutput = QtWidgets.QLabel(UserProfileDisplay)
        self.NicknameOutput.setGeometry(QtCore.QRect(280, 90, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.NicknameOutput.setFont(font)
        self.NicknameOutput.setStyleSheet("border-image: \\*url();")
        self.NicknameOutput.setObjectName("NicknameOutput")
        self.label_13 = QtWidgets.QLabel(UserProfileDisplay)
        self.label_13.setGeometry(QtCore.QRect(220, 220, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("border-image: \\*url();")
        self.label_13.setObjectName("label_13")
        self.BackButton = QtWidgets.QPushButton(UserProfileDisplay)
        self.BackButton.setGeometry(QtCore.QRect(10, 10, 80, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BackButton.setFont(font)
        self.BackButton.setStyleSheet("border-image: \\*url();")
        self.BackButton.setObjectName("BackButton")
        self.LastNameOutput = QtWidgets.QLabel(UserProfileDisplay)
        self.LastNameOutput.setGeometry(QtCore.QRect(320, 134, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LastNameOutput.setFont(font)
        self.LastNameOutput.setStyleSheet("border-image: \\*url();")
        self.LastNameOutput.setObjectName("LastNameOutput")
        self.label_12 = QtWidgets.QLabel(UserProfileDisplay)
        self.label_12.setGeometry(QtCore.QRect(380, 160, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("border-image: \\*url();")
        self.label_12.setObjectName("label_12")
        self.label_9 = QtWidgets.QLabel(UserProfileDisplay)
        self.label_9.setGeometry(QtCore.QRect(550, 130, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("border-image: \\*url();")
        self.label_9.setObjectName("label_9")
        self.label_14 = QtWidgets.QLabel(UserProfileDisplay)
        self.label_14.setGeometry(QtCore.QRect(557, 250, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("border-image: \\*url();")
        self.label_14.setObjectName("label_14")
        self.line = QtWidgets.QFrame(UserProfileDisplay)
        self.line.setGeometry(QtCore.QRect(520, 128, 2, 250))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line.setFont(font)
        self.line.setStyleSheet("border-image: \\*url();\n""background-color: rgb(19, 35, 255);\n""")
        self.line.setInputMethodHints(QtCore.Qt.ImhNone)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.DescriptionOutput = QtWidgets.QLabel(UserProfileDisplay)
        self.DescriptionOutput.setGeometry(QtCore.QRect(220, 250, 281, 121))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.DescriptionOutput.setFont(font)
        self.DescriptionOutput.setStyleSheet("border-image: \\*url();")
        self.DescriptionOutput.setWordWrap(True)
        self.DescriptionOutput.setObjectName("DescritionOutput")
        self.CityOutput = QtWidgets.QLabel(UserProfileDisplay)
        self.CityOutput.setGeometry(QtCore.QRect(270, 160, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.CityOutput.setFont(font)
        self.CityOutput.setStyleSheet("border-image: \\*url();")
        self.CityOutput.setObjectName("CityOutput")
        self.TagOutput = QtWidgets.QLabel(UserProfileDisplay)
        self.TagOutput.setGeometry(QtCore.QRect(430, 160, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.TagOutput.setFont(font)
        self.TagOutput.setStyleSheet("border-image: \\*url();")
        self.TagOutput.setObjectName("TagOutput")
        self.EmailAddressOutput = QtWidgets.QLabel(UserProfileDisplay)
        self.EmailAddressOutput.setGeometry(QtCore.QRect(350, 190, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EmailAddressOutput.setFont(font)
        self.EmailAddressOutput.setStyleSheet("border-image: \\*url();")
        self.EmailAddressOutput.setObjectName("EmailAddressOutput")

        self.AttendEvent1 = QtWidgets.QPushButton(UserProfileDisplay)
        self.AttendEvent1.setGeometry(QtCore.QRect(551, 150, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.AttendEvent1.setFont(font)
        self.AttendEvent1.setStyleSheet("border-image: \\*url();\n""background: transparent;\n""")
        self.AttendEvent1.setFlat(True)
        self.AttendEvent1.setObjectName("AttendEvent1")

        self.AttendEvent2 = QtWidgets.QPushButton(UserProfileDisplay)
        self.AttendEvent2.setGeometry(QtCore.QRect(551, 180, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.AttendEvent2.setFont(font)
        self.AttendEvent2.setStyleSheet("border-image: \\*url();\n""background: transparent;\n""")
        self.AttendEvent2.setFlat(True)
        self.AttendEvent2.setObjectName("AttendEvent2")

        self.AttendEvent3 = QtWidgets.QPushButton(UserProfileDisplay)
        self.AttendEvent3.setGeometry(QtCore.QRect(551, 210, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.AttendEvent3.setFont(font)
        self.AttendEvent3.setStyleSheet("border-image: \\*url();\n""background: transparent;\n""")
        self.AttendEvent3.setFlat(True)
        self.AttendEvent3.setObjectName("AttendEvent3")

        self.AttendEventList = [self.AttendEvent1, self.AttendEvent2, self.AttendEvent3]

        self.HostEvent1 = QtWidgets.QPushButton(UserProfileDisplay)
        self.HostEvent1.setGeometry(QtCore.QRect(551, 270, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.HostEvent1.setFont(font)
        self.HostEvent1.setStyleSheet("border-image: \\*url();\n""background: transparent;\n""")
        self.HostEvent1.setFlat(True)
        self.HostEvent1.setObjectName("HostEvent1")

        self.HostEvent2 = QtWidgets.QPushButton(UserProfileDisplay)
        self.HostEvent2.setGeometry(QtCore.QRect(552, 299, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.HostEvent2.setFont(font)
        self.HostEvent2.setStyleSheet("border-image: \\*url();\n""background: transparent;\n""")
        self.HostEvent2.setFlat(True)
        self.HostEvent2.setObjectName("HostEvent2")

        self.HostEvent3 = QtWidgets.QPushButton(UserProfileDisplay)
        self.HostEvent3.setGeometry(QtCore.QRect(552, 328, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.HostEvent3.setFont(font)
        self.HostEvent3.setStyleSheet("border-image: \\*url();\n""background: transparent;\n""")
        self.HostEvent3.setFlat(True)
        self.HostEvent3.setObjectName("HostEvent3")

        self.HostEventList = [self.HostEvent1, self.HostEvent2, self.HostEvent3]

        self.graphicsView = QtWidgets.QGraphicsView(UserProfileDisplay)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 745, 453))
        self.graphicsView.setStyleSheet("border-image: url(./bg.png)\n""\n""")
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.GenderOutput.raise_()
        self.FirstNameOutput.raise_()
        self.UserImageOutput.raise_()
        self.label_8.raise_()
        self.NicknameOutput.raise_()
        self.label_13.raise_()
        self.BackButton.raise_()
        self.LastNameOutput.raise_()
        self.label_12.raise_()
        self.label_9.raise_()
        self.label_14.raise_()
        self.line.raise_()
        self.DescriptionOutput.raise_()
        self.CityOutput.raise_()
        self.TagOutput.raise_()
        self.EmailAddressOutput.raise_()
        self.AttendEvent1.raise_()
        self.AttendEvent2.raise_()
        self.AttendEvent3.raise_()
        self.HostEvent1.raise_()
        self.HostEvent2.raise_()
        self.HostEvent3.raise_()

        self.retranslateUi(UserProfileDisplay)
        QtCore.QMetaObject.connectSlotsByName(UserProfileDisplay)

    def retranslateUi(self, UserProfileDisplay):
        _translate = QtCore.QCoreApplication.translate
        UserProfileDisplay.setWindowTitle(_translate("UserProfileDisplay", "Dialog"))
        self.label_2.setText(_translate("UserProfileDisplay", "JoinMe"))
        self.label_4.setText(_translate("UserProfileDisplay", "State"))
        self.GenderOutput.setText(_translate("UserProfileDisplay", ""))
        self.FirstNameOutput.setText(_translate("UserProfileDisplay", ""))
        self.label_8.setText(_translate("UserProfileDisplay", "Email Address"))
        self.NicknameOutput.setText(_translate("UserProfileDisplay", ""))
        self.label_13.setText(_translate("UserProfileDisplay", "Description:"))
        self.BackButton.setText(_translate("UserProfileDisplay", "Back"))
        self.LastNameOutput.setText(_translate("UserProfileDisplay", ""))
        self.label_12.setText(_translate("UserProfileDisplay", "Tags"))
        self.label_9.setText(_translate("UserProfileDisplay", "Event Attended"))
        self.label_14.setText(_translate("UserProfileDisplay", "Event Hosted"))
        self.DescriptionOutput.setText(_translate("UserProfileDisplay", ""))
        self.CityOutput.setText(_translate("UserProfileDisplay", ""))
        self.TagOutput.setText(_translate("UserProfileDisplay", ""))
        self.EmailAddressOutput.setText(_translate("UserProfileDisplay", ""))
        self.AttendEvent1.setText(_translate("UserProfileDisplay", ""))
        self.AttendEvent2.setText(_translate("UserProfileDisplay", ""))
        self.AttendEvent3.setText(_translate("UserProfileDisplay", ""))
        self.HostEvent1.setText(_translate("UserProfileDisplay", ""))
        self.HostEvent2.setText(_translate("UserProfileDisplay", ""))
        self.HostEvent3.setText(_translate("UserProfileDisplay", ""))
